export const CITIES = {
  sydney: {
    name: 'Sydney',
    state: 'NSW',
    stateFullName: 'New South Wales',
    medianHousePrice: '$1,620,000',
    medianUnitPrice: '$820,000',
    rentalYield: '2.9%',
    growthTrend: 'Long-term capital growth averaging 6–8% annually, driven by chronic undersupply and population growth.',
    marketSnapshot: "Sydney remains Australia's most expensive property market. Demand consistently outpaces supply, particularly within 20km of the CBD. Infrastructure investment – including Metro expansions and the Western Sydney Airport precinct – continues to drive growth in outer rings.",
    borrowingContext: "At Sydney's median house price of $1,620,000, a 20% deposit to avoid LMI is $324,000 – but most buyers don't need that. You can enter with as little as 5% ($81,000) through the federal First Home Guarantee, or potentially 0% using a guarantor loan. On a $120,000 household income you may borrow around $600,000 – $720,000 depending on expenses and lender. Many Sydney buyers target outer western suburbs – Penrith, Liverpool, Campbelltown – where entry prices start from $650,000.",
    grant: '$10,000',
    grantName: 'First Home Owner (New Homes) Grant',
    stampDutyNote: 'NSW has two main schemes. The First Home Owner (New Homes) Grant provides $10,000 towards a newly built home (no-one has lived in it before). The First Home Buyers Assistance Scheme provides a full stamp duty exemption on new or existing homes up to $800,000, and a concession on homes up to $1,000,000 – saving up to $30,000. Federally, the First Home Guarantee lets eligible buyers purchase with just 5% deposit and no LMI.',
    heroSub: 'Compare 40+ lenders and get mortgage advice from the JRW Finance team — buy sooner, borrow smarter, and avoid costly lending mistakes in one of Australia\'s most competitive markets.',
    suburbLinks: ['Parramatta', 'Blacktown', 'Penrith', 'Liverpool', 'Castle Hill', 'Chatswood', 'Campbelltown', 'Hornsby', 'Hurstville', 'Kogarah', 'Cronulla', 'Miranda'],
    cases: [
      {
        tag: 'First Home Buyer',
        heading: 'Entered the Sydney market with a 5% deposit and no LMI',
        body: 'Used the federal First Home Guarantee to avoid $31,000 in Lenders Mortgage Insurance. Pre-approved with two lenders simultaneously so they could move fast at auction.',
      },
      {
        tag: 'Property Investor',
        heading: 'Used equity in Parramatta unit to fund a second purchase',
        body: 'Structured a split loan to keep investment and owner-occupied debt separate, preserving full tax-deductible interest on the investment portion.',
      },
      {
        tag: 'Refinance',
        heading: 'Cut 1.4% off their rate after their loyalty discount expired',
        body: 'Moved from a Big 4 bank to a competitive non-bank lender with a full offset account. The rate reduction saves over $1,100 per month on their Sydney mortgage.',
      },
    ],
    faqs: [
      { q: 'Can I buy in Sydney with a 5% deposit?', a: "Yes. Through the federal First Home Guarantee scheme, eligible first home buyers can purchase with just a 5% deposit and avoid paying Lenders Mortgage Insurance (LMI) – saving $20,000–$40,000 in upfront costs. Income and property price caps apply. We assess your eligibility as part of your initial strategy call." },
      { q: 'How much can I borrow on a $120,000 salary in Sydney?', a: "On a $120,000 gross salary with typical living expenses, most lenders will assess borrowing capacity in the range of $600,000–$720,000 – though this varies significantly by lender, your expenses, existing debts and credit history. Some specialist lenders assess income differently and may offer more. We run your numbers across multiple lenders to find your real ceiling, not just one bank's answer." },
      { q: 'What Sydney suburbs qualify for first home buyer stamp duty exemptions?', a: "The NSW stamp duty exemption applies to the purchase price, not the suburb – new homes up to $800,000 are fully exempt, with concessions up to $1,000,000. This opens up options in many western and outer-ring suburbs including Penrith, Liverpool, Campbelltown, Blacktown and the Hills District. We map out which areas fit your budget and grant eligibility." },
      { q: 'How long does formal mortgage approval take in NSW?', a: "Once we submit a complete application, most lenders return formal approval within 3–10 business days for standard purchases. Complex scenarios – self-employed income, unusual property types, tight timeframes – can take longer. We prepare your application thoroughly upfront to avoid back-and-forth, and we know which lenders move fastest when time matters." },
      { q: 'Can I use equity from my Sydney property to buy an investment?', a: "Yes – and it's one of the most common strategies we help clients with. If your Sydney property has grown in value, you may be able to access that equity as a deposit for your next purchase without saving from scratch. We calculate your usable equity, identify the right loan structure and help you buy your next property without selling the first." },
    ],
  },

  melbourne: {
    name: 'Melbourne',
    state: 'VIC',
    stateFullName: 'Victoria',
    medianHousePrice: '$940,000',
    medianUnitPrice: '$620,000',
    rentalYield: '3.4%',
    growthTrend: 'Recovering strongly after a correction period, with Australia\'s fastest-growing population driving long-term demand.',
    marketSnapshot: "Melbourne is showing strong recovery signals after a correction period, underpinned by record interstate migration and undersupply in established suburbs. The outer growth corridor – Melton, Wyndham, Whittlesea – attracts first home buyers, while inner suburbs continue to deliver long-term capital growth.",
    borrowingContext: "At Melbourne's median house price of $940,000, a 10% deposit is $94,000 and 20% is $188,000. On a $100,000 household income you may borrow approximately $500,000–$600,000 depending on expenses and lender. Many first home buyers target the outer growth corridor – Werribee, Melton, Cranbourne – where entry prices start from $550,000, making a 10% deposit around $55,000.",
    grant: '$10,000',
    grantName: 'First Home Owner Grant',
    stampDutyNote: 'VIC first home buyers are exempt from stamp duty on homes up to $600,000, with concessions up to $750,000.',
    heroSub: 'Compare 40+ lenders and get Melbourne mortgage advice from the JRW Finance team — buy sooner, borrow smarter, and make the most of Victoria\'s first home buyer incentives.',
    suburbLinks: ['Footscray', 'St Kilda', 'Dandenong', 'Frankston', 'Werribee', 'Craigieburn', 'Ringwood', 'Sunshine', 'Berwick', 'Pakenham', 'Melton', 'Box Hill'],
    cases: [
      {
        tag: 'First Home Buyer',
        heading: 'Saved $31,070 in stamp duty on a Werribee townhouse',
        body: 'Purchased at $595,000 — just under the VIC stamp duty exemption threshold. Combined with the First Home Owner Grant, total upfront savings exceeded $41,000.',
      },
      {
        tag: 'Property Investor',
        heading: 'Restructured cross-collateralised loans to free up equity',
        body: 'Untangling properties held as cross-security with one bank unlocked $140,000 in usable equity, which was used to purchase a third investment property in Ringwood.',
      },
      {
        tag: 'Refinance',
        heading: 'Converted construction loan to standard variable and saved $890/month',
        body: 'After build completion, moved from a high-rate construction facility to a competitive variable with offset. The savings cleared their moving costs within three months.',
      },
    ],
    faqs: [
      { q: 'Can I buy in Melbourne with a 5% deposit?', a: "Yes. Through the federal First Home Guarantee, eligible first home buyers can purchase with a 5% deposit and avoid LMI – saving $15,000–$30,000 upfront. Property price caps apply in Victoria. We assess your eligibility as part of your strategy call." },
      { q: 'How much can I borrow on a $100,000 salary in Melbourne?', a: "On a $100,000 gross salary with typical expenses, most lenders assess borrowing capacity in the $500,000–$600,000 range – though this varies by lender, your debts and living costs. We run your numbers across multiple lenders to find your actual ceiling, not just one bank's figure." },
      { q: 'What Melbourne suburbs qualify for first home buyer stamp duty exemptions?', a: "The VIC stamp duty exemption applies to homes up to $600,000 regardless of suburb. This opens up options across Melbourne's outer ring – Melton, Wyndham, Frankston, Whittlesea – and many middle-ring suburbs for units. We map out what's achievable within your budget and exemption threshold." },
      { q: 'How long does mortgage approval take in Victoria?', a: "Most lenders return formal approval within 3–10 business days for a well-prepared application. We manage your documentation and lender communication end-to-end to avoid delays, and we know which lenders turn around fastest when auction dates are tight." },
      { q: 'Can I access equity from my Melbourne property to buy an investment?', a: "Yes – equity access is one of the most powerful tools available to Melbourne homeowners. If your property has grown in value, you may be able to fund an investment deposit without saving from scratch. We calculate your usable equity and structure the next purchase correctly." },
    ],
  },

  brisbane: {
    name: 'Brisbane',
    state: 'QLD',
    stateFullName: 'Queensland',
    medianHousePrice: '$860,000',
    medianUnitPrice: '$580,000',
    rentalYield: '4.1%',
    growthTrend: 'One of Australia\'s strongest-performing markets, with the 2032 Olympics and Cross River Rail driving sustained demand.',
    marketSnapshot: "Brisbane is in a prolonged growth phase driven by the 2032 Olympics, record interstate migration from NSW and Victoria, and major infrastructure including Cross River Rail and the Brisbane Metro. Inner-ring suburbs continue to see strong demand while outer areas offer accessible entry points for first home buyers.",
    borrowingContext: "At Brisbane's median of $860,000, a 10% deposit is $86,000 and 20% is $172,000. On a $90,000 household income you may borrow approximately $450,000–$550,000. For first home buyers, outer suburbs like Ipswich, Logan and Moreton Bay offer entry points from $550,000 – and Queensland's $30,000 First Home Owner Grant significantly reduces the deposit burden on new builds.",
    grant: '$30,000',
    grantName: 'Queensland First Home Owner Grant',
    stampDutyNote: 'QLD first home buyers pay no transfer duty on homes up to $700,000, with concessions up to $800,000.',
    heroSub: 'Compare 40+ lenders and capitalise on one of Australia\'s strongest property markets — expert mortgage advice from the JRW Finance team for Brisbane buyers and investors.',
    suburbLinks: ['Chermside', 'Sunnybank', 'Ipswich', 'Logan', 'North Lakes', 'Carindale', 'Toowoomba', 'Gold Coast'],
    cases: [
      {
        tag: 'First Home Buyer',
        heading: 'Combined the $30,000 QLD grant with a 5% deposit to enter North Lakes',
        body: 'Purchased a new build under the First Home Owner Grant. The $30,000 grant plus First Home Guarantee meant the clients needed to save less than $45,000 to get into a $590,000 home.',
      },
      {
        tag: 'Property Investor',
        heading: 'Secured an interest-only loan in a pre-Olympics growth corridor',
        body: 'Structured an IO investment loan on a Carindale property ahead of Olympics infrastructure spend. Rental income covers 94% of repayments, with strong capital growth expected through to 2032.',
      },
      {
        tag: 'Refinance',
        heading: 'Consolidated three investment loans and cut blended rate by 0.85%',
        body: 'Moved a three-property Brisbane portfolio from two separate banks to a single competitive lender. Simplified management, unlocked a lower rate, and freed up $380/month in cashflow.',
      },
    ],
    faqs: [
      { q: 'Can I buy in Brisbane with a 5% deposit?', a: "Yes. The federal First Home Guarantee allows eligible buyers to purchase with a 5% deposit and no LMI. Combined with Queensland's $30,000 First Home Owner Grant on new builds, first home buyers can enter the Brisbane market with significantly less upfront than most people expect. We assess your full eligibility on your first call." },
      { q: 'How much can I borrow on a $90,000 salary in Brisbane?', a: "On a $90,000 gross salary with typical expenses, most lenders assess borrowing capacity in the $450,000–$550,000 range. Brisbane's more accessible median prices compared to Sydney and Melbourne mean this budget opens up genuine options in outer suburbs and off-the-plan developments. We compare multiple lenders to find your real borrowing ceiling." },
      { q: 'What Brisbane suburbs are best for first home buyers in 2025?', a: "Logan, Ipswich, Moreton Bay and outer southern suburbs offer the best value for first home buyers – entry prices from $550,000 with strong rental demand and improving infrastructure. Cross River Rail and the Brisbane Metro are improving connectivity across these corridors, supporting long-term values. We help you identify the right area for your budget and goals." },
      { q: 'Is Brisbane still a good investment market given recent price growth?', a: "Brisbane's fundamentals remain strong: the 2032 Olympics infrastructure pipeline, record interstate migration, and tight rental vacancy (under 1.5%) continue to support values and rents. Entry prices, while higher than five years ago, remain well below Sydney and Melbourne for comparable properties. We structure investment loans to maximise your borrowing capacity and portfolio growth." },
      { q: 'Can I access equity from my Brisbane property to buy another investment?', a: "Yes – and many Brisbane homeowners are surprised how much equity they now hold after several years of strong growth. We calculate your usable equity, identify the right structure and help you use it as a deposit for your next purchase without needing to sell." },
    ],
  },

  perth: {
    name: 'Perth',
    state: 'WA',
    stateFullName: 'Western Australia',
    medianHousePrice: '$720,000',
    medianUnitPrice: '$460,000',
    rentalYield: '4.8%',
    growthTrend: 'Australia\'s top-performing market over three consecutive years, driven by resources sector strength and sub-1% vacancy rates.',
    marketSnapshot: "Perth has been Australia's standout property market since 2022, with some suburbs recording 50%+ growth. A booming resources sector, strong interstate migration and one of Australia's lowest vacancy rates (sub-1%) continue to drive prices and rents. Despite recent growth, Perth still offers significantly more affordable entry points than Sydney or Melbourne.",
    borrowingContext: "At Perth's median of $720,000, a 10% deposit is $72,000 and 20% is $144,000 – far more accessible than eastern capitals. On an $85,000 salary you may borrow approximately $420,000–$520,000. The outer ring – Ellenbrook, Baldivis, Yanchep, Armadale – offers entry prices from $450,000, with the METRONET expansion improving connectivity and supporting long-term values.",
    grant: '$10,000',
    grantName: 'First Home Owner Grant',
    stampDutyNote: 'WA first home buyers are exempt from stamp duty on homes up to $430,000, with concessions up to $530,000.',
    heroSub: 'Compare 40+ lenders and access Australia\'s strongest property market — expert mortgage advice from the JRW Finance team for Perth buyers and investors.',
    suburbLinks: ['Fremantle', 'Joondalup', 'Midland', 'Rockingham', 'Armadale', 'Mandurah', 'Baldivis', 'Ellenbrook'],
    cases: [
      {
        tag: 'First Home Buyer',
        heading: 'Purchased in Baldivis with a 5% deposit and no LMI',
        body: 'Used the federal First Home Guarantee to avoid over $18,000 in Lenders Mortgage Insurance. Formal approval came back in four business days — fast enough to secure the property before a competing offer.',
      },
      {
        tag: 'Property Investor',
        heading: 'FIFO worker unlocked $780,000 borrowing capacity using non-standard income',
        body: 'Resources sector income is assessed differently by lenders. By matching this client to a lender that recognised their full FIFO earnings, borrowing capacity increased by $160,000 compared to their original bank assessment.',
      },
      {
        tag: 'Refinance',
        heading: 'Switched to a non-bank lender and cleared $45,000 ahead of schedule',
        body: 'Moved from a Big 4 bank to a competitive non-bank with a 100% offset account. The rate saving combined with channelling surplus income through the offset cut two years off their loan term.',
      },
    ],
    faqs: [
      { q: 'Can I buy in Perth with a 5% deposit?', a: "Yes. Through the federal First Home Guarantee, eligible buyers can purchase with 5% deposit and no LMI. Perth's lower median prices also mean a 10–20% deposit is achievable faster than in Sydney or Melbourne. We assess your eligibility and identify the fastest path to purchase." },
      { q: 'How much can I borrow on an $85,000 salary in Perth?', a: "On an $85,000 gross salary with typical expenses, most lenders assess borrowing capacity in the $420,000–$520,000 range. In Perth, this budget opens up strong options in the outer ring – Ellenbrook, Baldivis, Rockingham – with good rental yields and growth potential. We compare multiple lenders to maximise your borrowing capacity." },
      { q: 'Is Perth still good value for investors after recent price growth?', a: "Perth still offers the highest rental yields of any Australian capital city, and entry prices remain well below Sydney and Melbourne. With vacancy rates under 1% and the METRONET expansion creating new growth corridors, the fundamentals for investors remain strong. We help you identify the right areas and structure your investment loan correctly." },
      { q: 'Can I buy a Perth property if I live interstate?', a: "Yes – we regularly help interstate buyers and investors purchase in Perth remotely. We manage the entire finance process, coordinate with local buyer's agents and settlement agents, and keep you informed at every step. Distance is not a barrier." },
      { q: 'How long does mortgage approval take in WA?', a: "For a well-prepared application, formal approval typically takes 3–7 business days with most lenders. We prepare everything upfront to avoid back-and-forth, and we know which WA lenders move fastest when settlement timelines are tight." },
    ],
  },

  adelaide: {
    name: 'Adelaide',
    state: 'SA',
    stateFullName: 'South Australia',
    medianHousePrice: '$760,000',
    medianUnitPrice: '$490,000',
    rentalYield: '4.5%',
    growthTrend: 'Consistently strong growth backed by defence investment, tight supply and affordability relative to eastern capitals.',
    marketSnapshot: "Adelaide has quietly become one of Australia's best-performing markets. Record defence and technology investment – led by the AUKUS submarine programme – strong population growth and a rental vacancy below 0.5% are driving sustained demand. Affordability relative to Sydney and Melbourne continues to attract interstate buyers and investors.",
    borrowingContext: "At Adelaide's median of $760,000, a 10% deposit is $76,000 and 20% is $152,000. On an $85,000 salary you may borrow approximately $420,000–$510,000. Many first home buyers target the northern and southern suburbs – Salisbury, Morphett Vale, Gawler – where entry prices start from $450,000, and SA's $15,000 First Home Owner Grant reduces upfront costs on new builds.",
    grant: '$15,000',
    grantName: 'First Home Owner Grant',
    stampDutyNote: 'SA first home buyers may be eligible for stamp duty concessions – thresholds vary by property type. We assess your eligibility.',
    heroSub: 'Compare 40+ lenders and access one of Australia\'s most underrated property markets — expert mortgage advice from the JRW Finance team for Adelaide buyers and investors.',
    suburbLinks: ['Glenelg', 'Norwood', 'Elizabeth', 'Mount Barker', 'Salisbury', 'Morphett Vale', 'Gawler', 'Victor Harbor'],
    cases: [
      {
        tag: 'First Home Buyer',
        heading: 'Combined the SA grant and stamp duty concession to save $25,000 upfront',
        body: 'Purchased a new build in Salisbury. The $15,000 First Home Owner Grant plus stamp duty concession reduced the cash needed at settlement by $25,000 — enough to keep a financial buffer in place post-purchase.',
      },
      {
        tag: 'Property Investor',
        heading: 'Defence contractor used dual-income assessment to purchase near Osborne Naval Shipyard',
        body: 'Both primary salary and supplementary contract income were assessed to increase borrowing capacity. The Osborne-adjacent property settled with a rental yield of 5.1% from day one.',
      },
      {
        tag: 'Refinance',
        heading: 'Rate cut of 1.2% on Adelaide Hills home with no break costs',
        body: 'The existing loan was variable, so there were no fixed-rate penalties to exit. Moved to a lower-rate lender with offset functionality. Monthly saving of $580 went straight onto principal.',
      },
    ],
    faqs: [
      { q: 'Can I buy in Adelaide with a 5% deposit?', a: "Yes. Through the federal First Home Guarantee you can purchase with a 5% deposit and avoid LMI. Adelaide's affordability also means saving a 10–20% deposit is more achievable here than in Sydney or Melbourne. We assess your full eligibility and map out the fastest path to purchase." },
      { q: 'How much can I borrow on an $85,000 salary in Adelaide?', a: "On an $85,000 gross salary with typical expenses, most lenders assess borrowing capacity in the $420,000–$510,000 range. In Adelaide, this opens up strong options across the northern and southern suburbs, with entry-level houses and townhouses available from $450,000. We compare multiple lenders to find your real ceiling." },
      { q: 'Why is Adelaide such a strong investment market right now?', a: "Adelaide combines sub-0.5% rental vacancy (the tightest in Australia), strong rental yields, affordable entry prices and significant government investment through the AUKUS submarine programme. This creates reliable cashflow for investors with a structural driver of demand – defence employment – that isn't going away." },
      { q: 'What Adelaide suburbs offer the best value for first home buyers?', a: "Salisbury, Elizabeth, Morphett Vale, Gawler and Mount Barker offer entry-level pricing with good transport links and amenities. The northern suburbs in particular benefit from proximity to Osborne Naval Shipyard employment, supporting long-term rental demand. We help you identify the right area for your budget and goals." },
      { q: 'Can I use my Adelaide property equity to buy an investment?', a: "Yes. With Adelaide's strong recent growth, many homeowners hold considerably more equity than they expect. We calculate your usable equity, structure the loan correctly and help you access it as a deposit for your next investment purchase." },
    ],
  },

  canberra: {
    name: 'Canberra',
    state: 'ACT',
    stateFullName: 'Australian Capital Territory',
    medianHousePrice: '$950,000',
    medianUnitPrice: '$590,000',
    rentalYield: '4.0%',
    growthTrend: 'Stable, low-volatility market underpinned by federal government employment and Australia\'s highest average household incomes.',
    marketSnapshot: "Canberra's market is underpinned by Australia's most stable employment base – federal government – and consistently high household incomes. Greenfield development in Gungahlin and Molonglo Valley meets demand for new housing, while inner suburbs like Braddon, Dickson and Kingston attract strong owner-occupier demand.",
    borrowingContext: "At Canberra's median of $950,000, a 10% deposit is $95,000 and 20% is $190,000. Canberra's high average household income – well above the national average – often supports stronger borrowing capacity than equivalent salaries elsewhere. The ACT's stamp duty abolition for eligible first home buyers through the Home Buyer Concession Scheme reduces upfront costs significantly.",
    grant: '$10,000',
    grantName: 'First Home Owner Grant',
    stampDutyNote: 'ACT has abolished stamp duty for eligible first home buyers through the Home Buyer Concession Scheme – income and property value thresholds apply.',
    heroSub: 'Compare 40+ lenders and get expert mortgage advice for Canberra buyers, investors and refinancers — the JRW Finance team understands the ACT market and public sector income structures.',
    suburbLinks: ['Belconnen', 'Gungahlin', 'Woden', 'Tuggeranong', 'Queanbeyan', 'Mawson', 'Braddon', 'Kingston'],
    cases: [
      {
        tag: 'First Home Buyer',
        heading: 'ACT stamp duty abolished under the Home Buyer Concession Scheme — $32,000 saved',
        body: 'A public servant purchasing in Gungahlin qualified under the Home Buyer Concession Scheme. Combined with careful lender selection, upfront costs were reduced by over $32,000 compared to a standard purchase.',
      },
      {
        tag: 'Property Investor',
        heading: 'Salary packaging included in income assessment — borrowing capacity up $60,000',
        body: 'Not all lenders treat ACT public service salary packaging the same way. Matching this client to the right lender increased their assessed income by $14,000, adding $60,000 to their borrowing capacity.',
      },
      {
        tag: 'Refinance',
        heading: 'Two Canberra properties moved to a single lender with 100% offset',
        body: 'Consolidating two loans at separate banks simplified repayments and unlocked a better rate. The 100% offset account now holds their emergency fund and reduces interest daily.',
      },
    ],
    faqs: [
      { q: 'Can I buy in Canberra with a 5% deposit?', a: "Yes. Eligible first home buyers can use the federal First Home Guarantee to purchase with a 5% deposit and no LMI. The ACT also has stamp duty abolished for eligible first home buyers through the Home Buyer Concession Scheme, which significantly reduces upfront purchase costs. We confirm your eligibility across both schemes." },
      { q: 'How much can I borrow on a $110,000 salary in Canberra?', a: "On a $110,000 gross salary – common in Canberra's public sector – most lenders assess borrowing capacity in the $560,000–$680,000 range depending on expenses and existing debts. Some lenders also treat certain government allowances as assessable income, potentially increasing your capacity. We run your numbers across multiple lenders." },
      { q: 'Does public service employment help with mortgage applications?', a: "Yes – significantly. Stable government income is viewed very favourably by lenders. It's predictable, salaried and low risk, which often translates to smoother approval processes and better rates. Some lenders also assess government allowances and salary packaging differently, which can improve your borrowing position." },
      { q: 'Is Canberra a good investment market?', a: "Canberra offers low vacancy rates, strong rental yields relative to entry prices, and a tenant base dominated by government employees and university students – both of which provide reliable rental income. It's a low-volatility, reliable buy-and-hold market. We help investors structure loans to maximise portfolio growth over time." },
      { q: 'Should I buy in Canberra or just over the border in Queanbeyan?', a: "Queanbeyan often offers lower entry prices with access to Canberra employment – but NSW and ACT grants, stamp duty rules and lending criteria differ significantly. The right answer depends on your specific budget, goals and eligibility. We compare both options for you and recommend the structure that genuinely saves the most." },
    ],
  },

  hobart: {
    name: 'Hobart',
    state: 'TAS',
    stateFullName: 'Tasmania',
    medianHousePrice: '$680,000',
    medianUnitPrice: '$460,000',
    rentalYield: '4.6%',
    growthTrend: 'Stabilising after a dramatic boom, with tight supply, tourism demand and lifestyle appeal continuing to underpin values.',
    marketSnapshot: "Hobart's market has settled after one of Australia's most dramatic property booms (2017–2022), where some suburbs doubled in value. Strong short-term rental demand from tourism, a growing creative and tech economy, and very tight supply continue to underpin values. Tasmania's $30,000 First Home Owner Grant is one of Australia's most generous.",
    borrowingContext: "At Hobart's median of $680,000, a 10% deposit is $68,000 and 20% is $136,000. On an $80,000 salary you may borrow approximately $390,000–$480,000. Outer suburbs and regional centres like Glenorchy, Clarence and Kingborough offer entry prices from $500,000, while Tasmania's generous $30,000 First Home Owner Grant significantly reduces upfront costs on new builds.",
    grant: '$30,000',
    grantName: 'First Home Owner Grant',
    stampDutyNote: 'TAS first home buyers are exempt from stamp duty on homes up to $750,000.',
    heroSub: 'Compare 40+ lenders and access one of Australia\'s most lifestyle-driven property markets — expert mortgage advice from the JRW Finance team for Hobart buyers and investors.',
    suburbLinks: ['Sandy Bay', 'Glenorchy', 'Kingborough', 'Clarence', 'Launceston', 'Devonport', 'Burnie', 'Huonville'],
    cases: [
      {
        tag: 'First Home Buyer',
        heading: 'TAS $30,000 grant and stamp duty exemption — entered Glenorchy with 7% deposit',
        body: 'The combination of Tasmania\'s generous First Home Owner Grant and stamp duty exemption reduced the upfront cash required at settlement by $43,000. Purchased a free-standing house in Glenorchy within six months of the first call.',
      },
      {
        tag: 'Property Investor',
        heading: 'Interstate buyer purchased remotely and achieved 7.2% short-term rental yield',
        body: 'A Melbourne-based investor purchased a Hobart townhouse without visiting in person. We managed the finance end-to-end, coordinating with a local buyer\'s agent. The property now runs as a short-term rental with a 7.2% gross yield.',
      },
      {
        tag: 'Refinance',
        heading: 'Switched from bank to non-bank — monthly saving of $670 with no clawback',
        body: 'The existing loan had no fixed rate, so there were no break costs to exit. Moved to a non-bank lender with a sharper rate and offset account. The saving of $670 per month is ahead of early estimates.',
      },
    ],
    faqs: [
      { q: 'Can I buy in Hobart with a 5% deposit?', a: "Yes. Through the federal First Home Guarantee, eligible buyers can purchase with a 5% deposit and no LMI. Combined with Tasmania's $30,000 First Home Owner Grant – one of Australia's most generous – first home buyers can enter the Hobart market with significantly less upfront than many expect. We assess your full eligibility." },
      { q: 'How much can I borrow on an $80,000 salary in Hobart?', a: "On an $80,000 gross salary with typical expenses, most lenders assess borrowing capacity in the $390,000–$480,000 range. Hobart's median prices are well below eastern capitals, meaning this budget opens up genuine options across the greater Hobart area, particularly in Glenorchy, Clarence and Kingborough." },
      { q: 'Is Hobart still a good investment after the market correction?', a: "Hobart's tight supply, strong tourism-driven short-term rental demand and lifestyle appeal continue to underpin values. Vacancy rates remain very low. For investors comfortable with a smaller, more niche market, Hobart offers attractive yields and a resilient tenant base. We help you identify the right property type and location." },
      { q: 'Can I buy in Hobart remotely as an interstate investor?', a: "Yes – we regularly assist interstate investors purchasing in Hobart remotely. We manage the finance end-to-end, coordinate with local buyer's agents and conveyancers, and keep you fully informed throughout. Distance doesn't have to be a barrier to a Tasmanian investment." },
      { q: 'What does stamp duty cost for first home buyers in Tasmania?', a: "First home buyers in Tasmania pay no stamp duty on purchases up to $750,000 – one of the most generous exemptions in the country. Combined with the $30,000 First Home Owner Grant on new builds, the upfront saving can be substantial. We confirm your exact eligibility and factor it into your full purchase plan." },
    ],
  },

  darwin: {
    name: 'Darwin',
    state: 'NT',
    stateFullName: 'Northern Territory',
    medianHousePrice: '$520,000',
    medianUnitPrice: '$330,000',
    rentalYield: '6.2%',
    growthTrend: 'Australia\'s highest rental yields, with improving market conditions driven by RAAF Base expansion and Ichthys LNG operations.',
    marketSnapshot: "Darwin offers Australia's highest rental yields – regularly exceeding 6% – combined with the most affordable median prices of any capital city. Major structural investment including the RAAF Base Darwin expansion, Ichthys LNG operations and Defence Housing Australia programmes provides an employment base that consistently drives rental demand.",
    borrowingContext: "At Darwin's median of $520,000, a 10% deposit is $52,000 and 20% is $104,000 – the most accessible entry point of any Australian capital. On a $75,000 salary you may borrow approximately $370,000–$450,000. The NT's Territory Home Owner Discount (up to $18,601) significantly reduces stamp duty costs for eligible buyers.",
    grant: '$10,000',
    grantName: 'First Home Owner Grant',
    stampDutyNote: 'NT first home buyers can access a $10,000 First Home Owner Grant plus a Territory Home Owner Discount of up to $18,601 on stamp duty.',
    heroSub: 'Access Australia\'s highest rental yields with expert mortgage advice from the JRW Finance team — compare 40+ lenders for your Darwin purchase.',
    suburbLinks: ['Palmerston', 'Casuarina', 'Nightcliff', 'Humpty Doo', 'Karama', 'Fannie Bay', 'Leanyer', 'Katherine'],
    cases: [
      {
        tag: 'First Home Buyer',
        heading: 'NT grant and Territory Home Owner Discount cut upfront costs by $28,601',
        body: 'The $10,000 First Home Owner Grant combined with the Territory Home Owner Discount on stamp duty reduced settlement costs significantly. The client purchased a free-standing house in Palmerston within their first year of saving.',
      },
      {
        tag: 'Property Investor',
        heading: 'Cashflow-positive from day one — 6.4% gross yield on Nightcliff house',
        body: 'Structured an interest-only investment loan on a Nightcliff property. Rental income covers all loan repayments and holding costs, with $340 per month positive cashflow. The client now holds two Darwin properties.',
      },
      {
        tag: 'Refinance',
        heading: 'DHA-leased property refinanced to a lower rate — lender selection was critical',
        body: 'Not all lenders accept Defence Housing Australia leases as standard rental income. We identified the right lender, refinanced the property at a sharper rate, and reduced monthly repayments by $490 without changing the lease terms.',
      },
    ],
    faqs: [
      { q: 'Can I buy in Darwin with a 5% deposit?', a: "Yes. Through the federal First Home Guarantee, eligible buyers can purchase with a 5% deposit and no LMI. Darwin's affordable median prices – the lowest of any Australian capital – also make saving a larger deposit achievable in a shorter timeframe. We assess your eligibility and chart the fastest path to purchase." },
      { q: 'How much can I borrow on a $75,000 salary in Darwin?', a: "On a $75,000 gross salary with typical expenses, most lenders assess borrowing capacity in the $370,000–$450,000 range. In Darwin, this budget opens up a wide range of free-standing houses in established suburbs – far more than the same budget would access in any other capital city. We compare lenders to find your real ceiling." },
      { q: "Why are Darwin's rental yields so high compared to other capitals?", a: "Darwin's yields reflect a unique supply-demand dynamic – a high-income, transient workforce from the ADF, resources sector and government creates consistent rental demand, while the small investor pool keeps property prices accessible. For cashflow-focused investors, yields of 5–7% on free-standing houses are achievable. We help you identify the right asset type and location." },
      { q: 'Is Darwin property too risky for investment?', a: "Darwin is a higher-volatility market than southern capitals – it has experienced significant cycles. The key is asset selection: free-standing houses in established suburbs (Nightcliff, Fannie Bay, Casuarina) consistently outperform units, and locations close to defence employment are more resilient. For investors focused on cashflow with a long-term horizon, the numbers can work very well." },
      { q: 'Can I buy a Darwin property if I live interstate?', a: "Yes – we regularly help interstate buyers and investors purchase in Darwin remotely. Some lenders apply different criteria for NT properties, so having a finance team that knows the market is especially valuable. We manage the entire process and know which lenders are most comfortable with Darwin lending." },
    ],
  },
}
