// Raw location data — key, display name, state, type, nearby suburbs
// type: 'regional' | 'metro' | 'coastal' | 'growth'
// parentCity: used in copy for metro suburbs

export const LOCATIONS = [
  // ─── NSW ──────────────────────────────────────────────
  { key: 'newcastle',       name: 'Newcastle',        state: 'NSW', type: 'regional',  subs: ['Hamilton', 'Broadmeadow', 'Charlestown', 'Kotara', 'Jesmond', 'Mayfield', 'Waratah', 'Wallsend'] },
  { key: 'wollongong',      name: 'Wollongong',       state: 'NSW', type: 'regional',  subs: ['Figtree', 'Fairy Meadow', 'Corrimal', 'Thirroul', 'Dapto', 'Albion Park', 'Shellharbour', 'Port Kembla'] },
  { key: 'central-coast',   name: 'Central Coast',    state: 'NSW', type: 'regional',  subs: ['Gosford', 'Wyong', 'Terrigal', 'Erina', 'Tuggerah', 'Umina Beach', 'Woy Woy', 'The Entrance'] },
  { key: 'maitland',        name: 'Maitland',         state: 'NSW', type: 'regional',  subs: ['East Maitland', 'Rutherford', 'Thornton', 'Metford', 'Cessnock', 'Kurri Kurri', 'Singleton', 'Branxton'] },
  { key: 'dubbo',           name: 'Dubbo',            state: 'NSW', type: 'regional',  subs: ['Narromine', 'Trangie', 'Wellington', 'Gilgandra', 'Peak Hill', 'Parkes', 'Forbes', 'Orange'] },
  { key: 'orange',          name: 'Orange',           state: 'NSW', type: 'regional',  subs: ['Bathurst', 'Blayney', 'Cowra', 'Parkes', 'Forbes', 'Molong', 'Canowindra', 'Manildra'] },
  { key: 'tamworth',        name: 'Tamworth',         state: 'NSW', type: 'regional',  subs: ['Gunnedah', 'Quirindi', 'Narrabri', 'Armidale', 'Walcha', 'Manilla', 'Werris Creek', 'Moonbi'] },
  { key: 'albury',          name: 'Albury',           state: 'NSW', type: 'regional',  subs: ['Lavington', 'Thurgoona', 'Wodonga', 'Baranduda', 'Beechworth', 'Wangaratta', 'Corowa', 'Mulwala'] },
  { key: 'wagga-wagga',     name: 'Wagga Wagga',      state: 'NSW', type: 'regional',  subs: ['Tolland', 'Turvey Park', 'Glenfield Park', 'Forest Hill', 'Estella', 'Tatton', 'Bourkelands', 'Springvale'] },
  { key: 'port-macquarie',  name: 'Port Macquarie',   state: 'NSW', type: 'coastal',   subs: ['Wauchope', 'Laurieton', 'Kempsey', 'Taree', 'Forster', 'Tuncurry', 'Lake Cathie', 'Bonny Hills'] },
  { key: 'coffs-harbour',   name: 'Coffs Harbour',    state: 'NSW', type: 'coastal',   subs: ['Sawtell', 'Toormina', 'Woolgoolga', 'Grafton', 'Maclean', 'Yamba', 'Bellingen', 'Urunga'] },
  { key: 'bathurst',        name: 'Bathurst',         state: 'NSW', type: 'regional',  subs: ['Orange', 'Oberon', 'Blayney', 'Lithgow', 'Mudgee', 'Cowra', 'Crookwell', 'Tarana'] },
  { key: 'lismore',         name: 'Lismore',          state: 'NSW', type: 'regional',  subs: ['Ballina', 'Byron Bay', 'Casino', 'Kyogle', 'Bangalow', 'Alstonville', 'Goonellabah', 'Lennox Head'] },
  { key: 'armidale',        name: 'Armidale',         state: 'NSW', type: 'regional',  subs: ['Uralla', 'Guyra', 'Walcha', 'Inverell', 'Glen Innes', 'Tenterfield', 'Moree', 'Narrabri'] },
  { key: 'nowra',           name: 'Nowra',            state: 'NSW', type: 'coastal',   subs: ['Bomaderry', 'Vincentia', 'Culburra Beach', 'Huskisson', 'Ulladulla', 'Batemans Bay', 'Berry', 'Kangaroo Valley'] },
  { key: 'bowral',          name: 'Bowral',           state: 'NSW', type: 'regional',  subs: ['Mittagong', 'Moss Vale', 'Robertson', 'Bundanoon', 'Berrima', 'Sutton Forest', 'Burradoo', 'Exeter'] },
  { key: 'mudgee',          name: 'Mudgee',           state: 'NSW', type: 'regional',  subs: ['Gulgong', 'Rylstone', 'Kandos', 'Dunedoo', 'Coolah', 'Merriwa', 'Sandy Hollow', 'Ulan'] },
  { key: 'goulburn',        name: 'Goulburn',         state: 'NSW', type: 'regional',  subs: ['Marulan', 'Crookwell', 'Taralga', 'Tarago', 'Bungonia', 'Collector', 'Gunning', 'Yass'] },
  { key: 'batemans-bay',    name: 'Batemans Bay',     state: 'NSW', type: 'coastal',   subs: ['Moruya', 'Narooma', 'Broulee', 'Tomakin', 'Ulladulla', 'Mollymook', 'Mogo', 'Nelligen'] },
  // Sydney metro suburbs
  { key: 'parramatta',      name: 'Parramatta',       state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Westmead', 'Harris Park', 'Granville', 'Merrylands', 'Guildford', 'Auburn', 'Silverwater', 'Rosehill'] },
  { key: 'blacktown',       name: 'Blacktown',        state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Seven Hills', 'Toongabbie', 'Kings Park', 'Marayong', 'Quakers Hill', 'Stanhope Gardens', 'Doonside', 'Woodcroft'] },
  { key: 'penrith',         name: 'Penrith',          state: 'NSW', type: 'growth',    parentCity: 'Sydney', subs: ['St Marys', 'Kingswood', 'Werrington', 'Emu Plains', 'Glenmore Park', 'Cranebrook', 'Cambridge Park', 'Leonay'] },
  { key: 'liverpool',       name: 'Liverpool',        state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Casula', 'Moorebank', 'Prestons', 'Chipping Norton', 'Lurnea', 'Miller', 'Hinchinbrook', 'Warwick Farm'] },
  { key: 'campbelltown',    name: 'Campbelltown',     state: 'NSW', type: 'growth',    parentCity: 'Sydney', subs: ['Airds', 'Minto', 'Ingleburn', 'Macquarie Fields', 'Ruse', 'Blair Athol', 'Rosemeadow', 'Eagle Vale'] },
  { key: 'bankstown',       name: 'Bankstown',        state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Yagoona', 'Punchbowl', 'Roselands', 'Padstow', 'Revesby', 'Panania', 'East Hills', 'Milperra'] },
  { key: 'chatswood',       name: 'Chatswood',        state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Willoughby', 'Artarmon', 'Lane Cove', 'St Leonards', 'Crows Nest', 'North Sydney', 'Roseville', 'Lindfield'] },
  { key: 'hornsby',         name: 'Hornsby',          state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Waitara', 'Mount Colah', 'Asquith', 'Berowra', 'Brooklyn', 'Galston', 'Pennant Hills', 'Cherrybrook'] },
  { key: 'hurstville',      name: 'Hurstville',       state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Kogarah', 'Rockdale', 'Bexley', 'Kingsgrove', 'Beverly Hills', 'Narwee', 'Penshurst', 'Mortdale'] },
  { key: 'sutherland',      name: 'Sutherland',       state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Cronulla', 'Miranda', 'Caringbah', 'Gymea', 'Menai', 'Bangor', 'Engadine', 'Heathcote'] },
  { key: 'manly',           name: 'Manly',            state: 'NSW', type: 'coastal',   parentCity: 'Sydney', subs: ['Dee Why', 'Brookvale', 'Narraweena', 'Curl Curl', 'Freshwater', 'Fairlight', 'Queenscliff', 'Balgowlah'] },
  { key: 'bondi',           name: 'Bondi',            state: 'NSW', type: 'coastal',   parentCity: 'Sydney', subs: ['Bondi Junction', 'Randwick', 'Coogee', 'Maroubra', 'Kingsford', 'Kensington', 'Paddington', 'Waverley'] },
  { key: 'north-sydney',    name: 'North Sydney',     state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Crows Nest', 'St Leonards', 'Artarmon', 'Neutral Bay', 'Mosman', 'Cremorne', 'Kirribilli', 'Lavender Bay'] },
  { key: 'ryde',            name: 'Ryde',             state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Meadowbank', 'Shepherds Bay', 'West Ryde', 'Eastwood', 'Epping', 'Macquarie Park', 'North Ryde', 'Gladesville'] },
  { key: 'castle-hill',     name: 'Castle Hill',      state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Baulkham Hills', 'Norwest', 'Bella Vista', 'Kellyville', 'Rouse Hill', 'Box Hill', 'Glenhaven', 'Dural'] },

  // ─── VIC ──────────────────────────────────────────────
  { key: 'geelong',         name: 'Geelong',          state: 'VIC', type: 'regional',  subs: ['Newtown', 'Belmont', 'Corio', 'Norlane', 'Lara', 'Leopold', 'Ocean Grove', 'Barwon Heads'] },
  { key: 'ballarat',        name: 'Ballarat',         state: 'VIC', type: 'regional',  subs: ['Wendouree', 'Delacombe', 'Lucas', 'Sebastopol', 'Alfredton', 'Buninyong', 'Mount Clear', 'Smythes Creek'] },
  { key: 'bendigo',         name: 'Bendigo',          state: 'VIC', type: 'regional',  subs: ['Strathfieldsaye', 'Kangaroo Flat', 'Eaglehawk', 'White Hills', 'Flora Hill', 'Epsom', 'Junortoun', 'Maiden Gully'] },
  { key: 'shepparton',      name: 'Shepparton',       state: 'VIC', type: 'regional',  subs: ['Mooroopna', 'Kialla', 'Tatura', 'Echuca', 'Kyabram', 'Cobram', 'Numurkah', 'Yarrawonga'] },
  { key: 'traralgon',       name: 'Traralgon',        state: 'VIC', type: 'regional',  subs: ['Morwell', 'Moe', 'Churchill', 'Sale', 'Bairnsdale', 'Lakes Entrance', 'Leongatha', 'Warragul'] },
  { key: 'mildura',         name: 'Mildura',          state: 'VIC', type: 'regional',  subs: ['Irymple', 'Merbein', 'Red Cliffs', 'Wentworth', 'Renmark', 'Robinvale', 'Swan Hill', 'Ouyen'] },
  { key: 'warrnambool',     name: 'Warrnambool',      state: 'VIC', type: 'coastal',   subs: ['Dennington', 'Allansford', 'Koroit', 'Port Fairy', 'Camperdown', 'Terang', 'Colac', 'Hamilton'] },
  { key: 'wodonga',         name: 'Wodonga',          state: 'VIC', type: 'regional',  subs: ['Albury', 'Baranduda', 'Beechworth', 'Wangaratta', 'Corowa', 'Rutherglen', 'Tallangatta', 'Yackandandah'] },
  { key: 'mornington',      name: 'Mornington',       state: 'VIC', type: 'coastal',   parentCity: 'Melbourne', subs: ['Rosebud', 'Rye', 'Sorrento', 'Portsea', 'Safety Beach', 'Dromana', 'Mount Martha', 'Frankston'] },
  // Melbourne metro
  { key: 'dandenong',       name: 'Dandenong',        state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Springvale', 'Noble Park', 'Keysborough', 'Doveton', 'Endeavour Hills', 'Hallam', 'Bangholme', 'Lyndhurst'] },
  { key: 'frankston',       name: 'Frankston',        state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Langwarrin', 'Seaford', 'Carrum Downs', 'Skye', 'Sandhurst', 'Cranbourne', 'Baxter', 'Leawarra'] },
  { key: 'ringwood',        name: 'Ringwood',         state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Croydon', 'Mooroolbark', 'Boronia', 'Bayswater', 'Ferntree Gully', 'Heathmont', 'Vermont', 'Warranwood'] },
  { key: 'box-hill',        name: 'Box Hill',         state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Nunawading', 'Mitcham', 'Blackburn', 'Forest Hill', 'Burwood', 'Mount Waverley', 'Glen Waverley', 'Doncaster'] },
  { key: 'sunshine',        name: 'Sunshine',         state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Footscray', 'Altona', 'Laverton', 'Hoppers Crossing', 'Werribee', 'Tarneit', 'Truganina', 'Williams Landing'] },
  { key: 'berwick',         name: 'Berwick',          state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['Narre Warren', 'Pakenham', 'Officer', 'Beaconsfield', 'Harkaway', 'Clyde', 'Clyde North', 'Cranbourne'] },
  { key: 'craigieburn',     name: 'Craigieburn',      state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['Mickleham', 'Kalkallo', 'Donnybrook', 'Roxburgh Park', 'Broadmeadows', 'Coolaroo', 'Dallas', 'Glenroy'] },
  { key: 'epping',          name: 'Epping',           state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['South Morang', 'Mill Park', 'Lalor', 'Thomastown', 'Bundoora', 'Wollert', 'Doreen', 'Mernda'] },
  { key: 'werribee',        name: 'Werribee',         state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['Hoppers Crossing', 'Wyndham Vale', 'Tarneit', 'Truganina', 'Point Cook', 'Laverton', 'Altona Meadows', 'Williamstown'] },

  // ─── QLD ──────────────────────────────────────────────
  { key: 'gold-coast',      name: 'Gold Coast',       state: 'QLD', type: 'coastal',   subs: ['Surfers Paradise', 'Broadbeach', 'Burleigh Heads', 'Robina', 'Southport', 'Helensvale', 'Nerang', 'Mudgeeraba'] },
  { key: 'sunshine-coast',  name: 'Sunshine Coast',   state: 'QLD', type: 'coastal',   subs: ['Maroochydore', 'Caloundra', 'Noosa', 'Nambour', 'Buderim', 'Kawana Waters', 'Sippy Downs', 'Palmview'] },
  { key: 'townsville',      name: 'Townsville',       state: 'QLD', type: 'regional',  subs: ['Thuringowa', 'Kirwan', 'Idalia', 'Annandale', 'Mount Louisa', 'Cranbrook', 'Oonoonba', 'Heatley'] },
  { key: 'cairns',          name: 'Cairns',           state: 'QLD', type: 'regional',  subs: ['Smithfield', 'Redlynch', 'Gordonvale', 'Woree', 'Brinsmead', 'Kewarra Beach', 'Trinity Beach', 'Palm Cove'] },
  { key: 'toowoomba',       name: 'Toowoomba',        state: 'QLD', type: 'regional',  subs: ['Harristown', 'Newtown', 'Rangeville', 'Highfields', 'Cotswold Hills', 'Glenvale', 'Kearneys Spring', 'Mount Lofty'] },
  { key: 'rockhampton',     name: 'Rockhampton',      state: 'QLD', type: 'regional',  subs: ['Gracemere', 'Norman Gardens', 'Berserker', 'Frenchville', 'Mount Morgan', 'Yeppoon', 'Emu Park', 'Zilzie'] },
  { key: 'mackay',          name: 'Mackay',           state: 'QLD', type: 'regional',  subs: ['North Mackay', 'South Mackay', 'Andergrove', 'Rural View', 'Glenella', 'Mount Pleasant', 'Beaconsfield', 'Ooralea'] },
  { key: 'bundaberg',       name: 'Bundaberg',        state: 'QLD', type: 'regional',  subs: ['Kepnock', 'Avenell Heights', 'Walkervale', 'Norville', 'Thabeban', 'Svensson Heights', 'Bargara', 'Burnett Heads'] },
  { key: 'hervey-bay',      name: 'Hervey Bay',       state: 'QLD', type: 'coastal',   subs: ['Urangan', 'Torquay', 'Pialba', 'Scarness', 'Eli Waters', 'Kawungan', 'Point Vernon', 'Maryborough'] },
  { key: 'gladstone',       name: 'Gladstone',        state: 'QLD', type: 'regional',  subs: ['Clinton', 'Tannum Sands', 'Boyne Island', 'Calliope', 'Kin Kora', 'New Auckland', 'Sun Valley', 'Toolooa'] },
  { key: 'noosa',           name: 'Noosa',            state: 'QLD', type: 'coastal',   subs: ['Noosa Heads', 'Noosaville', 'Tewantin', 'Cooroy', 'Pomona', 'Peregian Beach', 'Marcus Beach', 'Sunshine Beach'] },
  // Brisbane metro
  { key: 'ipswich',         name: 'Ipswich',          state: 'QLD', type: 'growth',    parentCity: 'Brisbane', subs: ['Springfield', 'Springfield Lakes', 'Redbank Plains', 'Collingwood Park', 'Ripley', 'Camira', 'Goodna', 'Wacol'] },
  { key: 'logan',           name: 'Logan',            state: 'QLD', type: 'growth',    parentCity: 'Brisbane', subs: ['Marsden', 'Beenleigh', 'Browns Plains', 'Waterford', 'Daisy Hill', 'Shailer Park', 'Springwood', 'Tanah Merah'] },
  { key: 'north-lakes',     name: 'North Lakes',      state: 'QLD', type: 'growth',    parentCity: 'Brisbane', subs: ['Mango Hill', 'Murrumba Downs', 'Dakabin', 'Kallangur', 'Petrie', 'Strathpine', 'Brendale', 'Lawnton'] },
  { key: 'redcliffe',       name: 'Redcliffe',        state: 'QLD', type: 'coastal',   parentCity: 'Brisbane', subs: ['Margate', 'Woody Point', 'Kippa-Ring', 'Rothwell', 'Clontarf', 'Deception Bay', 'Scarborough', 'Newport'] },
  { key: 'caboolture',      name: 'Caboolture',       state: 'QLD', type: 'growth',    parentCity: 'Brisbane', subs: ['Morayfield', 'Narangba', 'Burpengary', 'Elimbah', 'Wamuran', 'Pumicestone', 'Glass House Mountains', 'Woodford'] },

  // ─── WA ───────────────────────────────────────────────
  { key: 'bunbury',         name: 'Bunbury',          state: 'WA',  type: 'regional',  subs: ['Australind', 'Eaton', 'Carey Park', 'College Grove', 'Glen Iris', 'Dalyellup', 'Stratham', 'Harvey'] },
  { key: 'albany',          name: 'Albany',           state: 'WA',  type: 'coastal',   subs: ['Yakamia', 'Lockyer', 'Lange', 'Gledhow', 'Centennial Park', 'Bayonet Head', 'Collingwood Park', 'Spencer Park'] },
  { key: 'geraldton',       name: 'Geraldton',        state: 'WA',  type: 'regional',  subs: ['Rangeway', 'Spalding', 'Wandina', 'Strathalbyn', 'Bluff Point', 'Beresford', 'Mahomets Flats', 'Karloo'] },
  { key: 'kalgoorlie',      name: 'Kalgoorlie',       state: 'WA',  type: 'regional',  subs: ['Boulder', 'Hannans', 'Piccadilly', 'Lamington', 'Somerville', 'West Kalgoorlie', 'Karlkurla', 'Brown Hill'] },
  { key: 'mandurah',        name: 'Mandurah',         state: 'WA',  type: 'coastal',   subs: ['Halls Head', 'Falcon', 'Greenfields', 'Meadow Springs', 'Dudley Park', 'Lakelands', 'Madora Bay', 'Erskine'] },
  { key: 'rockingham',      name: 'Rockingham',       state: 'WA',  type: 'metro',     parentCity: 'Perth', subs: ['Baldivis', 'Safety Bay', 'Shoalwater', 'Waikiki', 'Warnbro', 'Port Kennedy', 'Secret Harbour', 'Golden Bay'] },
  { key: 'joondalup',       name: 'Joondalup',        state: 'WA',  type: 'metro',     parentCity: 'Perth', subs: ['Edgewater', 'Currambine', 'Ocean Reef', 'Heathridge', 'Connolly', 'Beldon', 'Duncraig', 'Padbury'] },
  { key: 'fremantle',       name: 'Fremantle',        state: 'WA',  type: 'metro',     parentCity: 'Perth', subs: ['North Fremantle', 'East Fremantle', 'White Gum Valley', 'Beaconsfield', 'Hamilton Hill', 'Spearwood', 'Coolbellup', 'Hilton'] },
  { key: 'midland',         name: 'Midland',          state: 'WA',  type: 'metro',     parentCity: 'Perth', subs: ['Middle Swan', 'Guildford', 'Bassendean', 'Bayswater', 'Morley', 'Noranda', 'Beechboro', 'Bennett Springs'] },
  { key: 'karratha',        name: 'Karratha',         state: 'WA',  type: 'regional',  subs: ['Nickol', 'Bulgarra', 'Pegs Creek', 'Millars Well', 'Baynton', 'Tambrey', 'Dampier', 'Point Samson'] },

  // ─── SA ───────────────────────────────────────────────
  { key: 'gawler',          name: 'Gawler',           state: 'SA',  type: 'growth',    parentCity: 'Adelaide', subs: ['Evanston', 'Evanston Park', 'Hillier', 'Reid', 'Two Wells', 'Hewett', 'Munno Para', 'Angle Vale'] },
  { key: 'mount-barker',    name: 'Mount Barker',     state: 'SA',  type: 'growth',    parentCity: 'Adelaide', subs: ['Nairne', 'Hahndorf', 'Littlehampton', 'Meadows', 'Strathalbyn', 'Woodside', 'Balhannah', 'Verdun'] },
  { key: 'mount-gambier',   name: 'Mount Gambier',    state: 'SA',  type: 'regional',  subs: ['Millicent', 'Penola', 'Naracoorte', 'Bordertown', 'Casterton', 'Lucindale', 'Beachport', 'Robe'] },
  { key: 'whyalla',         name: 'Whyalla',          state: 'SA',  type: 'regional',  subs: ['Port Augusta', 'Port Pirie', 'Port Lincoln', 'Cowell', 'Kimba', 'Cleve', 'Streaky Bay', 'Ceduna'] },
  { key: 'victor-harbor',   name: 'Victor Harbor',    state: 'SA',  type: 'coastal',   subs: ['Goolwa', 'Port Elliot', 'Middleton', 'Hindmarsh Island', 'Encounter Bay', 'Hayborough', 'Mount Compass', 'Currency Creek'] },
  { key: 'morphett-vale',   name: 'Morphett Vale',    state: 'SA',  type: 'metro',     parentCity: 'Adelaide', subs: ['Christies Beach', 'Noarlunga', 'Seaford', 'Hackham', 'Onkaparinga Hills', 'Woodcroft', 'Aberfoyle Park', 'Reynella'] },
  { key: 'salisbury',       name: 'Salisbury',        state: 'SA',  type: 'metro',     parentCity: 'Adelaide', subs: ['Elizabeth', 'Davoren Park', 'Paralowie', 'Parafield Gardens', 'Pooraka', 'Brahma Lodge', 'Mawson Lakes', 'Ingle Farm'] },

  // ─── TAS ──────────────────────────────────────────────
  { key: 'launceston',      name: 'Launceston',       state: 'TAS', type: 'regional',  subs: ['Newnham', 'Riverside', 'Youngtown', 'Prospect', 'Kings Meadows', 'Ravenswood', 'Invermay', 'Hadspen'] },
  { key: 'devonport',       name: 'Devonport',        state: 'TAS', type: 'coastal',   subs: ['East Devonport', 'Spreyton', 'Shorewell Park', 'Quoiba', 'Wivenhoe', 'Penguin', 'Ulverstone', 'Latrobe'] },
  { key: 'burnie',          name: 'Burnie',           state: 'TAS', type: 'regional',  subs: ['Somerset', 'Wynyard', 'Ulverstone', 'Penguin', 'Cam', 'East Cam', 'Upper Burnie', 'Cooee'] },

  // ─── NT ───────────────────────────────────────────────
  { key: 'alice-springs',   name: 'Alice Springs',    state: 'NT',  type: 'regional',  subs: ['Larapinta', 'Desert Springs', 'Gillen', 'Sadadeen', 'Braitling', 'Ross', 'Araluen', 'Ciccone'] },
  { key: 'palmerston',      name: 'Palmerston',       state: 'NT',  type: 'growth',    parentCity: 'Darwin', subs: ['Farrar', 'Gunn', 'Rosebery', 'Woodroffe', 'Johnston', 'Durack', 'Marlow Lagoon', 'Driver'] },

  // ─── ACT / BORDER ─────────────────────────────────────
  { key: 'queanbeyan',      name: 'Queanbeyan',       state: 'NSW', type: 'regional',  subs: ['Jerrabomberra', 'Googong', 'Karabar', 'Greenleigh', 'Crestwood', 'Tralee', 'Royalla', 'Carwoola'] },
  { key: 'tuggeranong',     name: 'Tuggeranong',      state: 'ACT', type: 'metro',     parentCity: 'Canberra', subs: ['Greenway', 'Kambah', 'Macgregor', 'Wanniassa', 'Fadden', 'Calwell', 'Isabella Plains', 'Theodore'] },
  { key: 'belconnen',       name: 'Belconnen',        state: 'ACT', type: 'metro',     parentCity: 'Canberra', subs: ['Bruce', 'Hawker', 'Florey', 'Macquarie', 'Cook', 'Weetangera', 'Scullin', 'Evatt'] },
  { key: 'gungahlin',       name: 'Gungahlin',        state: 'ACT', type: 'growth',    parentCity: 'Canberra', subs: ['Franklin', 'Harrison', 'Ngunnawal', 'Palmerston', 'Amaroo', 'Forde', 'Casey', 'Bonner'] },

  // ─── Additional high-value locations ──────────────────
  { key: 'byron-bay',       name: 'Byron Bay',        state: 'NSW', type: 'coastal',   subs: ['Bangalow', 'Mullumbimby', 'Brunswick Heads', 'Lennox Head', 'Ballina', 'Suffolk Park', 'Ewingsdale', 'Newrybar'] },
  { key: 'tweed-heads',     name: 'Tweed Heads',      state: 'NSW', type: 'coastal',   subs: ['Coolangatta', 'Bilinga', 'Banora Point', 'Murwillumbah', 'Cabarita Beach', 'Pottsville', 'Kingscliff', 'Casuarina'] },
  { key: 'lake-macquarie',  name: 'Lake Macquarie',   state: 'NSW', type: 'regional',  subs: ['Charlestown', 'Kotara', 'Glendale', 'Cardiff', 'Warners Bay', 'Belmont', 'Swansea', 'Morisset'] },
  { key: 'ballina',         name: 'Ballina',          state: 'NSW', type: 'coastal',   subs: ['Lennox Head', 'East Ballina', 'West Ballina', 'Alstonville', 'Wardell', 'Tintenbar', 'Wollongbar', 'Empire Vale'] },
  { key: 'broken-hill',     name: 'Broken Hill',      state: 'NSW', type: 'regional',  subs: ['Silverton', 'Menindee', 'Wilcannia', 'Cobar', 'White Cliffs', 'Tibooburra', 'Wentworth', 'Dareton'] },
  { key: 'griffith',        name: 'Griffith',         state: 'NSW', type: 'regional',  subs: ['Leeton', 'Narrandera', 'Hay', 'Hillston', 'West Wyalong', 'Lake Cargelligo', 'Temora', 'Barmedman'] },
  { key: 'bathurst-region', name: 'Bathurst Region',  state: 'NSW', type: 'regional',  subs: ['Bathurst', 'Orange', 'Lithgow', 'Blayney', 'Oberon', 'Sofala', 'Hill End', 'Rockley'] },
  { key: 'hunter-valley',   name: 'Hunter Valley',    state: 'NSW', type: 'regional',  subs: ['Cessnock', 'Maitland', 'Singleton', 'Branxton', 'Kurri Kurri', 'Aberdare', 'Weston', 'Heddon Greta'] },
  { key: 'wollert',         name: 'Wollert',          state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['Doreen', 'Mernda', 'Epping', 'South Morang', 'Mill Park', 'Lalor', 'Thomastown', 'Plenty'] },
  { key: 'point-cook',      name: 'Point Cook',       state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['Hoppers Crossing', 'Williams Landing', 'Altona Meadows', 'Laverton', 'Truganina', 'Tarneit', 'Werribee', 'Wyndham Vale'] },
  { key: 'south-morang',    name: 'South Morang',     state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['Mill Park', 'Lalor', 'Thomastown', 'Bundoora', 'Wollert', 'Doreen', 'Mernda', 'Epping'] },
  { key: 'pakenham',        name: 'Pakenham',         state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['Officer', 'Beaconsfield', 'Clyde', 'Clyde North', 'Berwick', 'Narre Warren', 'Cranbourne', 'Cardinia'] },
  { key: 'melton',          name: 'Melton',           state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['Kurunjang', 'Brookfield', 'Aintree', 'Strathtulloh', 'Thornhill Park', 'Eynesbury', 'Toolern Vale', 'Rockbank'] },
  { key: 'sunbury',         name: 'Sunbury',          state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['Diggers Rest', 'Bulla', 'Riddells Creek', 'Gisborne', 'Macedon', 'Romsey', 'Lancefield', 'Clarkefield'] },
  { key: 'ocean-grove',     name: 'Ocean Grove',      state: 'VIC', type: 'coastal',   subs: ['Barwon Heads', 'Torquay', 'Jan Juc', 'Anglesea', 'Aireys Inlet', 'Lorne', 'Apollo Bay', 'Queenscliff'] },
  { key: 'torquay',         name: 'Torquay',          state: 'VIC', type: 'coastal',   subs: ['Jan Juc', 'Bells Beach', 'Anglesea', 'Aireys Inlet', 'Lorne', 'Ocean Grove', 'Barwon Heads', 'Queenscliff'] },
  { key: 'healesville',     name: 'Healesville',      state: 'VIC', type: 'regional',  subs: ['Yarra Glen', 'Lilydale', 'Coldstream', 'Dixons Creek', 'Yering', 'Steels Creek', 'Wandin North', 'Woori Yallock'] },
  { key: 'broadbeach',      name: 'Broadbeach',       state: 'QLD', type: 'coastal',   parentCity: 'Gold Coast', subs: ['Mermaid Beach', 'Miami', 'Burleigh Heads', 'Palm Beach', 'Currumbin', 'Tallebudgera', 'Elanora', 'Varsity Lakes'] },
  { key: 'robina',          name: 'Robina',           state: 'QLD', type: 'metro',     parentCity: 'Gold Coast', subs: ['Varsity Lakes', 'Mudgeeraba', 'Reedy Creek', 'Merrimac', 'Worongary', 'Nerang', 'Highland Park', 'Clear Island Waters'] },
  { key: 'southport',       name: 'Southport',        state: 'QLD', type: 'metro',     parentCity: 'Gold Coast', subs: ['Labrador', 'Biggera Waters', 'Runaway Bay', 'Coombabah', 'Paradise Point', 'Hollywell', 'Helensvale', 'Arundel'] },
  { key: 'springfield',     name: 'Springfield',      state: 'QLD', type: 'growth',    parentCity: 'Brisbane', subs: ['Springfield Lakes', 'Augustine Heights', 'Brookwater', 'Ipswich', 'Redbank Plains', 'Collingwood Park', 'Ripley', 'Camira'] },
  { key: 'coomera',         name: 'Coomera',          state: 'QLD', type: 'growth',    parentCity: 'Gold Coast', subs: ['Upper Coomera', 'Ormeau', 'Pimpama', 'Jacobs Well', 'Helensvale', 'Oxenford', 'Maudsland', 'Willow Vale'] },
  { key: 'maroochydore',    name: 'Maroochydore',     state: 'QLD', type: 'coastal',   subs: ['Mooloolaba', 'Alexandra Headland', 'Buddina', 'Kawana Waters', 'Bokarina', 'Wurtulla', 'Birtinya', 'Sippy Downs'] },
  { key: 'caloundra',       name: 'Caloundra',        state: 'QLD', type: 'coastal',   subs: ['Mooloolaba', 'Kawana Waters', 'Currimundi', 'Little Mountain', 'Kings Beach', 'Pelican Waters', 'Aroona', 'Birtinya'] },
  { key: 'mount-isa',       name: 'Mount Isa',        state: 'QLD', type: 'regional',  subs: ['Cloncurry', 'Camooweal', 'Dajarra', 'Boulia', 'Winton', 'Longreach', 'Barcaldine', 'Alpha'] },
  { key: 'port-hedland',    name: 'Port Hedland',     state: 'WA',  type: 'regional',  subs: ['South Hedland', 'Wedgefield', 'Boodarie', 'Broome', 'Karratha', 'Tom Price', 'Newman', 'Marble Bar'] },
  { key: 'broome',          name: 'Broome',           state: 'WA',  type: 'coastal',   subs: ['Cable Beach', 'Roebuck', 'Djugun', 'Pelican', 'Pilarong', 'Coconut Wells', 'Bilingurr', 'Port Hedland'] },
  { key: 'esperance',       name: 'Esperance',        state: 'WA',  type: 'coastal',   subs: ['Salmon Gums', 'Norseman', 'Kalgoorlie', 'Ravensthorpe', 'Hopetoun', 'Gibson', 'Castletown', 'Myrup'] },
  { key: 'margaret-river',  name: 'Margaret River',   state: 'WA',  type: 'coastal',   subs: ['Busselton', 'Dunsborough', 'Cowaramup', 'Yallingup', 'Augusta', 'Witchcliffe', 'Prevelly', 'Gracetown'] },
  { key: 'port-lincoln',    name: 'Port Lincoln',     state: 'SA',  type: 'coastal',   subs: ['Boston', 'Tumby Bay', 'Coffin Bay', 'Wangary', 'Cummins', 'Streaky Bay', 'Ceduna', 'Whyalla'] },
  { key: 'barossa',         name: 'Barossa Valley',   state: 'SA',  type: 'regional',  subs: ['Tanunda', 'Nuriootpa', 'Angaston', 'Lyndoch', 'Williamstown', 'Kapunda', 'Gawler', 'Greenock'] },
  { key: 'murray-bridge',   name: 'Murray Bridge',    state: 'SA',  type: 'regional',  subs: ['Mannum', 'Tailem Bend', 'Meningie', 'Wellington', 'Callington', 'Monarto South', 'Mobilong', 'Mypolonga'] },
  { key: 'uluru',           name: 'Uluru Region',     state: 'NT',  type: 'regional',  subs: ['Yulara', 'Alice Springs', 'Kings Canyon', 'Erldunda', 'Curtin Springs', 'Docker River', 'Mutitjulu', 'Imanpa'] },
  { key: 'katherine',       name: 'Katherine',        state: 'NT',  type: 'regional',  subs: ['Palmerston', 'Darwin', 'Tennant Creek', 'Mataranka', 'Larrimah', 'Daly Waters', 'Elliott', 'Borroloola'] },
  { key: 'port-stephens',   name: 'Port Stephens',    state: 'NSW', type: 'coastal',   subs: ['Nelson Bay', 'Shoal Bay', 'Anna Bay', 'Fingal Bay', 'Salamander Bay', 'Medowie', 'Raymond Terrace', 'Taylors Beach'] },
  { key: 'forster',         name: 'Forster',          state: 'NSW', type: 'coastal',   subs: ['Tuncurry', 'Pacific Palms', 'Hallidays Point', 'Harrington', 'Taree', 'Old Bar', 'Coopernook', 'Coolongolook'] },
  { key: 'kiama',           name: 'Kiama',            state: 'NSW', type: 'coastal',   subs: ['Gerringong', 'Berry', 'Gerroa', 'Jamberoo', 'Minnamurra', 'Albion Park', 'Shell Cove', 'Windang'] },
  { key: 'ulladulla',       name: 'Ulladulla',        state: 'NSW', type: 'coastal',   subs: ['Mollymook', 'Milton', 'Batemans Bay', 'Bendalong', 'Manyana', 'Sussex Inlet', 'Hyams Beach', 'Huskisson'] },
  { key: 'moruya',          name: 'Moruya',           state: 'NSW', type: 'coastal',   subs: ['Narooma', 'Bodalla', 'Tuross Head', 'Potato Point', 'Congo', 'Batemans Bay', 'Tilba', 'Bermagui'] },
  { key: 'yeppoon',         name: 'Yeppoon',          state: 'QLD', type: 'coastal',   subs: ['Emu Park', 'Keppel Sands', 'Byfield', 'Kinka Beach', 'Cooee Bay', 'Zilzie', 'Rockhampton', 'Farnborough'] },
  { key: 'airlie-beach',    name: 'Airlie Beach',     state: 'QLD', type: 'coastal',   subs: ['Cannonvale', 'Proserpine', 'Bowen', 'Collinsville', 'Home Hill', 'Ayr', 'Glenella', 'Mount Pleasant'] },

  // ─── Additional NSW suburbs ───────────────────────────
  { key: 'strathfield',     name: 'Strathfield',      state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Homebush', 'Flemington', 'Burwood', 'Croydon', 'Ashfield', 'Concord', 'Rhodes', 'North Strathfield'] },
  { key: 'auburn',          name: 'Auburn',           state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Lidcombe', 'Granville', 'Merrylands', 'Woodville', 'Berala', 'Regents Park', 'Chester Hill', 'Sefton'] },
  { key: 'epping-nsw',      name: 'Epping',           state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['North Epping', 'Eastwood', 'Carlingford', 'Dundas', 'Telopea', 'Rydalmere', 'West Ryde', 'Meadowbank'] },
  { key: 'dee-why',         name: 'Dee Why',          state: 'NSW', type: 'coastal',   parentCity: 'Sydney', subs: ['Brookvale', 'Narraweena', 'Curl Curl', 'Collaroy', 'Cromer', 'Wheeler Heights', 'Beacon Hill', 'Allambie Heights'] },
  { key: 'cronulla',        name: 'Cronulla',         state: 'NSW', type: 'coastal',   parentCity: 'Sydney', subs: ['Caringbah', 'Miranda', 'Gymea', 'Woolooware', 'Burraneer', 'Kurnell', 'Bundeena', 'Maianbar'] },
  { key: 'marrickville',    name: 'Marrickville',     state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Newtown', 'Erskineville', 'St Peters', 'Sydenham', 'Tempe', 'Dulwich Hill', 'Petersham', 'Leichhardt'] },
  { key: 'randwick',        name: 'Randwick',         state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Coogee', 'Maroubra', 'Clovelly', 'Kingsford', 'Kensington', 'Bronte', 'South Coogee', 'Little Bay'] },
  { key: 'kogarah',         name: 'Kogarah',          state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Rockdale', 'Arncliffe', 'Bexley', 'Hurstville', 'Allawah', 'Carlton', 'Carss Park', 'Ramsgate'] },
  { key: 'mosman',          name: 'Mosman',           state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Cremorne', 'Neutral Bay', 'Kirribilli', 'Milsons Point', 'Lavender Bay', 'North Sydney', 'Waverton', 'Cammeray'] },
  { key: 'baulkham-hills',  name: 'Baulkham Hills',   state: 'NSW', type: 'metro',     parentCity: 'Sydney', subs: ['Norwest', 'Bella Vista', 'Castle Hill', 'Kellyville', 'Winston Hills', 'Seven Hills', 'Old Toongabbie', 'Girraween'] },
  { key: 'kellyville',      name: 'Kellyville',       state: 'NSW', type: 'growth',    parentCity: 'Sydney', subs: ['Rouse Hill', 'Box Hill', 'Stanhope Gardens', 'Beaumont Hills', 'Norwest', 'Bella Vista', 'Schofields', 'Riverstone'] },
  { key: 'schofields',      name: 'Schofields',       state: 'NSW', type: 'growth',    parentCity: 'Sydney', subs: ['Riverstone', 'Marsden Park', 'The Ponds', 'Rouse Hill', 'Tallawong', 'Quakers Hill', 'Colebee', 'Grantham Farm'] },
  { key: 'gregory-hills',   name: 'Gregory Hills',    state: 'NSW', type: 'growth',    parentCity: 'Sydney', subs: ['Gledswood Hills', 'Oran Park', 'Leppington', 'Mount Annan', 'Narellan', 'Camden', 'Spring Farm', 'Elderslie'] },
  { key: 'oran-park',       name: 'Oran Park',        state: 'NSW', type: 'growth',    parentCity: 'Sydney', subs: ['Gregory Hills', 'Gledswood Hills', 'Leppington', 'Cobbitty', 'Narellan', 'Camden', 'Spring Farm', 'Catherine Field'] },
  { key: 'narellan',        name: 'Narellan',         state: 'NSW', type: 'growth',    parentCity: 'Sydney', subs: ['Camden', 'Spring Farm', 'Mount Annan', 'Harrington Park', 'Kirkham', 'Currans Hill', 'Cobbitty', 'Elderslie'] },

  // ─── Additional VIC suburbs ───────────────────────────
  { key: 'doncaster',       name: 'Doncaster',        state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Templestowe', 'Warrandyte', 'Park Orchards', 'Donvale', 'Bulleen', 'Nunawading', 'Mitcham', 'Box Hill North'] },
  { key: 'glen-waverley',   name: 'Glen Waverley',    state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Mulgrave', 'Wheelers Hill', 'Rowville', 'Scoresby', 'Knoxfield', 'Brandon Park', 'Mount Waverley', 'Burwood East'] },
  { key: 'lilydale',        name: 'Lilydale',         state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Mooroolbark', 'Croydon', 'Kilsyth', 'Mount Evelyn', 'Chirnside Park', 'Coldstream', 'Yering', 'Seville'] },
  { key: 'narre-warren',    name: 'Narre Warren',     state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['Berwick', 'Cranbourne', 'Clyde', 'Clyde North', 'Fountain Gate', 'Hampton Park', 'Endeavour Hills', 'Hallam'] },
  { key: 'caroline-springs',name: 'Caroline Springs', state: 'VIC', type: 'growth',    parentCity: 'Melbourne', subs: ['Taylors Lakes', 'Keilor East', 'Watergardens', 'Taylors Hill', 'Hillside', 'Plumpton', 'Kings Park', 'Delahey'] },
  { key: 'bundoora',        name: 'Bundoora',         state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Mill Park', 'Kingsbury', 'Macleod', 'Greensborough', 'Watsonia', 'Montmorency', 'Briar Hill', 'St Helena'] },
  { key: 'williamstown',    name: 'Williamstown',     state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Newport', 'Altona', 'Altona North', 'Spotswood', 'South Kingsville', 'Seabrook', 'Laverton', 'Williamstown North'] },
  { key: 'st-kilda',        name: 'St Kilda',         state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Elwood', 'Balaclava', 'Ripponlea', 'Elsternwick', 'Caulfield', 'Brighton', 'Middle Park', 'Albert Park'] },
  { key: 'richmond-vic',    name: 'Richmond',         state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Cremorne', 'Abbotsford', 'Collingwood', 'Fitzroy', 'Northcote', 'Burnley', 'Hawthorn', 'Toorak'] },
  { key: 'footscray',       name: 'Footscray',        state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Seddon', 'Yarraville', 'Kingsville', 'Spotswood', 'Newport', 'West Footscray', 'Maidstone', 'Braybrook'] },
  { key: 'cheltenham',      name: 'Cheltenham',       state: 'VIC', type: 'metro',     parentCity: 'Melbourne', subs: ['Mentone', 'Mordialloc', 'Highett', 'Moorabbin', 'Heatherton', 'Parkdale', 'Dingley Village', 'Braeside'] },
  { key: 'geelong-west',    name: 'Geelong West',     state: 'VIC', type: 'regional',  subs: ['Manifold Heights', 'Herne Hill', 'Hamlyn Heights', 'Norlane', 'Bell Post Hill', 'Corio', 'Lara', 'North Geelong'] },
  { key: 'armstrong-creek', name: 'Armstrong Creek',  state: 'VIC', type: 'growth',    subs: ['Charlemont', 'Grovedale', 'Marshall', 'Waurn Ponds', 'Mount Duneed', 'Torquay', 'Jan Juc', 'Belmont'] },

  // ─── Additional QLD ───────────────────────────────────
  { key: 'beenleigh',       name: 'Beenleigh',        state: 'QLD', type: 'growth',    parentCity: 'Brisbane', subs: ['Logan', 'Waterford', 'Eagleby', 'Mount Warren Park', 'Bahrs Scrub', 'Windaroo', 'Bannockburn', 'Loganholme'] },
  { key: 'browns-plains',   name: 'Browns Plains',    state: 'QLD', type: 'growth',    parentCity: 'Brisbane', subs: ['Marsden', 'Hillcrest', 'Regents Park', 'Park Ridge', 'Heritage Park', 'Crestmead', 'Forestdale', 'Boronia Heights'] },
  { key: 'oxenford',        name: 'Oxenford',         state: 'QLD', type: 'growth',    parentCity: 'Gold Coast', subs: ['Helensvale', 'Maudsland', 'Coomera', 'Upper Coomera', 'Pacific Pines', 'Arundel', 'Parkwood', 'Molendinar'] },
  { key: 'pimpama',         name: 'Pimpama',          state: 'QLD', type: 'growth',    parentCity: 'Gold Coast', subs: ['Coomera', 'Upper Coomera', 'Ormeau', 'Jacobs Well', 'Yatala', 'Stapylton', 'Norwell', 'Woongoolba'] },
  { key: 'buderim',         name: 'Buderim',          state: 'QLD', type: 'metro',     parentCity: 'Sunshine Coast', subs: ['Sippy Downs', 'Palmview', 'Kawana Waters', 'Mooloolaba', 'Alexandra Headland', 'Mountain Creek', 'Forest Glen', 'Kunda Park'] },
  { key: 'palm-beach-qld',  name: 'Palm Beach',       state: 'QLD', type: 'coastal',   parentCity: 'Gold Coast', subs: ['Currumbin', 'Elanora', 'Varsity Lakes', 'Tugun', 'Bilinga', 'Coolangatta', 'Burleigh Heads', 'Tallebudgera'] },
  { key: 'maryborough',     name: 'Maryborough',      state: 'QLD', type: 'regional',  subs: ['Hervey Bay', 'Gympie', 'Tiaro', 'Howard', 'Torbanlea', 'Childers', 'Biggenden', 'Mungar'] },
  { key: 'gympie',          name: 'Gympie',           state: 'QLD', type: 'regional',  subs: ['Noosa', 'Cooroy', 'Pomona', 'Tin Can Bay', 'Rainbow Beach', 'Maryborough', 'Kilkivan', 'Imbil'] },

  // ─── Additional WA ────────────────────────────────────
  { key: 'armadale',        name: 'Armadale',         state: 'WA',  type: 'growth',    parentCity: 'Perth', subs: ['Byford', 'Mundijong', 'Kelmscott', 'Gosnells', 'Maddington', 'Camillo', 'Seville Grove', 'Bedfordale'] },
  { key: 'baldivis',        name: 'Baldivis',         state: 'WA',  type: 'growth',    parentCity: 'Perth', subs: ['Karnup', 'Lakelands', 'Secret Harbour', 'Golden Bay', 'Port Kennedy', 'Safety Bay', 'Waikiki', 'Warnbro'] },
  { key: 'ellenbrook',      name: 'Ellenbrook',       state: 'WA',  type: 'growth',    parentCity: 'Perth', subs: ['The Vines', 'Brabham', 'Dayton', 'Aveley', 'Henley Brook', 'Upper Swan', 'West Swan', 'Whiteman'] },
  { key: 'butler',          name: 'Butler',           state: 'WA',  type: 'growth',    parentCity: 'Perth', subs: ['Ridgewood', 'Banksia Grove', 'Merriwa', 'Jindalee', 'Quinns Rocks', 'Clarkson', 'Mindarie', 'Tamala Park'] },
  { key: 'wanneroo',        name: 'Wanneroo',         state: 'WA',  type: 'growth',    parentCity: 'Perth', subs: ['Sinagra', 'Tapping', 'Ashby', 'Darch', 'Madeley', 'Hocking', 'Pearsall', 'Gnangara'] },

  // ─── Additional SA ────────────────────────────────────
  { key: 'elizabeth',       name: 'Elizabeth',        state: 'SA',  type: 'metro',     parentCity: 'Adelaide', subs: ['Davoren Park', 'Smithfield', 'Paralowie', 'Andrews Farm', 'Craigmore', 'Blakeview', 'Munno Para', 'Angle Vale'] },
  { key: 'modbury',         name: 'Modbury',          state: 'SA',  type: 'metro',     parentCity: 'Adelaide', subs: ['Tea Tree Gully', 'Ridgehaven', 'Banksia Park', 'Greenwith', 'Golden Grove', 'Fairview Park', 'Dernancourt', 'Vista'] },
  { key: 'mount-barker-sa', name: 'Mount Barker',     state: 'SA',  type: 'growth',    parentCity: 'Adelaide', subs: ['Nairne', 'Hahndorf', 'Littlehampton', 'Meadows', 'Strathalbyn', 'Woodside', 'Balhannah', 'Verdun'] },
  { key: 'port-augusta',    name: 'Port Augusta',     state: 'SA',  type: 'regional',  subs: ['Whyalla', 'Port Pirie', 'Quorn', 'Hawker', 'Parachilna', 'Leigh Creek', 'Peterborough', 'Orroroo'] },

  // ─── Additional TAS ───────────────────────────────────
  { key: 'kingborough',     name: 'Kingborough',      state: 'TAS', type: 'metro',     parentCity: 'Hobart', subs: ['Kingston', 'Blackmans Bay', 'Huntingfield', 'Taroona', 'Margate', 'Snug', 'Woodbridge', 'Kettering'] },
  { key: 'clarence',        name: 'Clarence',         state: 'TAS', type: 'metro',     parentCity: 'Hobart', subs: ['Rokeby', 'Howrah', 'Bellerive', 'Mornington', 'Warrane', 'Risdon Vale', 'Montagu Bay', 'Oakdowns'] },
  { key: 'glenorchy',       name: 'Glenorchy',        state: 'TAS', type: 'metro',     parentCity: 'Hobart', subs: ['Moonah', 'New Town', 'Derwent Park', 'Goodwood', 'Claremont', 'Austins Ferry', 'Berriedale', 'Collinsvale'] },

  // ─── Lifestyle/coastal high-value ─────────────────────
  { key: 'noosa-heads',     name: 'Noosa Heads',      state: 'QLD', type: 'coastal',   subs: ['Noosaville', 'Tewantin', 'Sunshine Beach', 'Peregian Beach', 'Marcus Beach', 'Cooroibah', 'Boreen Point', 'Lake Weyba'] },
  { key: 'palm-beach-nsw',  name: 'Palm Beach',       state: 'NSW', type: 'coastal',   parentCity: 'Sydney', subs: ['Avalon', 'Bilgola', 'Newport', 'Mona Vale', 'Narrabeen', 'Collaroy', 'Dee Why', 'Warriewood'] },
  { key: 'avalon',          name: 'Avalon Beach',     state: 'NSW', type: 'coastal',   parentCity: 'Sydney', subs: ['Palm Beach', 'Bilgola', 'Newport', 'Ingleside', 'Bayview', 'Mona Vale', 'Warriewood', 'Elanora Heights'] },
  { key: 'bowral-highlands',name: 'Southern Highlands',state: 'NSW',type: 'regional',  subs: ['Bowral', 'Mittagong', 'Moss Vale', 'Robertson', 'Bundanoon', 'Berrima', 'Sutton Forest', 'Burradoo'] },
  { key: 'blue-mountains',  name: 'Blue Mountains',   state: 'NSW', type: 'regional',  subs: ['Katoomba', 'Leura', 'Springwood', 'Penrith', 'Lithgow', 'Blackheath', 'Wentworth Falls', 'Blaxland'] },
  { key: 'hunter-region',   name: 'Hunter Region',    state: 'NSW', type: 'regional',  subs: ['Newcastle', 'Maitland', 'Cessnock', 'Singleton', 'Muswellbrook', 'Scone', 'Merriwa', 'Dungog'] },
  { key: 'illawarra',       name: 'Illawarra',        state: 'NSW', type: 'regional',  subs: ['Wollongong', 'Shellharbour', 'Kiama', 'Gerringong', 'Berry', 'Nowra', 'Bomaderry', 'Ulladulla'] },
  { key: 'riverina',        name: 'Riverina',         state: 'NSW', type: 'regional',  subs: ['Wagga Wagga', 'Griffith', 'Narrandera', 'Leeton', 'Hay', 'Deniliquin', 'Albury', 'Tumut'] },
  { key: 'new-england',     name: 'New England',      state: 'NSW', type: 'regional',  subs: ['Tamworth', 'Armidale', 'Glen Innes', 'Inverell', 'Tenterfield', 'Uralla', 'Walcha', 'Guyra'] },
  { key: 'far-north-coast', name: 'Far North Coast',  state: 'NSW', type: 'coastal',   subs: ['Byron Bay', 'Ballina', 'Lismore', 'Grafton', 'Yamba', 'Tweed Heads', 'Murwillumbah', 'Kingscliff'] },
  { key: 'surf-coast',      name: 'Surf Coast',       state: 'VIC', type: 'coastal',   subs: ['Torquay', 'Jan Juc', 'Anglesea', 'Aireys Inlet', 'Lorne', 'Apollo Bay', 'Winchelsea', 'Moriac'] },
  { key: 'bellarine',       name: 'Bellarine Peninsula',state: 'VIC',type: 'coastal',  subs: ['Ocean Grove', 'Barwon Heads', 'Queenscliff', 'Point Lonsdale', 'Portarlington', 'Indented Head', 'St Leonards', 'Clifton Springs'] },
  { key: 'mornington-peninsula',name:'Mornington Peninsula',state:'VIC',type:'coastal',subs:['Mornington','Rosebud','Rye','Sorrento','Portsea','Mount Martha','Safety Beach','Dromana'] },
  { key: 'yarra-valley',    name: 'Yarra Valley',     state: 'VIC', type: 'regional',  subs: ['Healesville', 'Yarra Glen', 'Lilydale', 'Warburton', 'Seville', 'Coldstream', 'Wandin North', 'Launching Place'] },
  { key: 'fraser-coast',    name: 'Fraser Coast',     state: 'QLD', type: 'coastal',   subs: ['Hervey Bay', 'Maryborough', 'Urangan', 'Torquay', 'Howard', 'Tiaro', 'Childers', 'Gin Gin'] },
  { key: 'whitsundays',     name: 'Whitsundays',      state: 'QLD', type: 'coastal',   subs: ['Airlie Beach', 'Cannonvale', 'Bowen', 'Proserpine', 'Collinsville', 'Home Hill', 'Ayr', 'Mount Pleasant'] },
  { key: 'tablelands',      name: 'Tablelands',       state: 'QLD', type: 'regional',  subs: ['Atherton', 'Mareeba', 'Malanda', 'Millaa Millaa', 'Yungaburra', 'Ravenshoe', 'Mount Garnet', 'Herberton'] },
  { key: 'south-west-wa',   name: 'South West WA',    state: 'WA',  type: 'coastal',   subs: ['Busselton', 'Dunsborough', 'Margaret River', 'Cowaramup', 'Yallingup', 'Augusta', 'Nannup', 'Bridgetown'] },
  { key: 'great-southern',  name: 'Great Southern',   state: 'WA',  type: 'regional',  subs: ['Albany', 'Denmark', 'Mount Barker WA', 'Kojonup', 'Katanning', 'Narrogin', 'Wagin', 'Broomehill'] },

  // ─── Final top-up to 250 ──────────────────────────────
  { key: 'liverpool-plains', name: 'Liverpool Plains', state: 'NSW', type: 'regional', subs: ['Quirindi', 'Werris Creek', 'Willow Tree', 'Tamworth', 'Narrabri', 'Gunnedah', 'Boggabri', 'Mullaley'] },
  { key: 'mid-north-coast',  name: 'Mid North Coast',  state: 'NSW', type: 'coastal',  subs: ['Port Macquarie', 'Kempsey', 'Nambucca Heads', 'Coffs Harbour', 'Bellingen', 'Grafton', 'Macksville', 'Urunga'] },
  { key: 'snowy-mountains',  name: 'Snowy Mountains',  state: 'NSW', type: 'regional', subs: ['Jindabyne', 'Cooma', 'Berridale', 'Adaminaby', 'Bombala', 'Perisher', 'Thredbo', 'Tumut'] },
  { key: 'shoalhaven',       name: 'Shoalhaven',       state: 'NSW', type: 'coastal',  subs: ['Nowra', 'Huskisson', 'Ulladulla', 'Batemans Bay', 'Berry', 'Kangaroo Valley', 'Culburra Beach', 'Sussex Inlet'] },
  { key: 'north-richmond',   name: 'Richmond',         state: 'NSW', type: 'growth',   parentCity: 'Sydney', subs: ['Windsor', 'McGraths Hill', 'Vineyard', 'Mulgrave', 'Riverstone', 'Marsden Park', 'Schofields', 'Wilberforce'] },
  { key: 'appin',            name: 'Appin',            state: 'NSW', type: 'growth',   parentCity: 'Sydney', subs: ['Wilton', 'Menangle Park', 'Mount Gilead', 'Campbelltown', 'Spring Farm', 'Picton', 'Thirlmere', 'Tahmoor'] },
  { key: 'mount-druitt',     name: 'Mount Druitt',     state: 'NSW', type: 'metro',    parentCity: 'Sydney', subs: ['Rooty Hill', 'Bidwill', 'Tregear', 'Whalan', 'Emerton', 'Hebersham', 'Blackett', 'Willmot'] },
  { key: 'fairfield',        name: 'Fairfield',        state: 'NSW', type: 'metro',    parentCity: 'Sydney', subs: ['Cabramatta', 'Canley Vale', 'Wetherill Park', 'Bossley Park', 'Prairiewood', 'Smithfield', 'Edensor Park', 'Green Valley'] },
  { key: 'springfield-nsw',  name: 'Springfield',      state: 'NSW', type: 'growth',   parentCity: 'Sydney', subs: ['Norwest', 'Bella Vista', 'Baulkham Hills', 'Castle Hill', 'Kellyville', 'Glenwood', 'Woodcroft', 'Stanhope Gardens'] },
  { key: 'south-coast-nsw',  name: 'South Coast',      state: 'NSW', type: 'coastal',  subs: ['Nowra', 'Batemans Bay', 'Ulladulla', 'Narooma', 'Bega', 'Eden', 'Merimbula', 'Pambula'] },
  { key: 'wagga-surrounds',  name: 'Wagga Surrounds',  state: 'NSW', type: 'regional', subs: ['Wagga Wagga', 'Junee', 'Temora', 'Cootamundra', 'Harden', 'Young', 'Cowra', 'Blayney'] },
  { key: 'penrith-region',   name: 'Penrith Region',   state: 'NSW', type: 'growth',   parentCity: 'Sydney', subs: ['Penrith', 'St Marys', 'Werrington', 'Emu Plains', 'Glenmore Park', 'Jordan Springs', 'Werrington County', 'Colyton'] },
  { key: 'geelong-east',     name: 'Geelong East',     state: 'VIC', type: 'regional', subs: ['Bell Park', 'Bell Post Hill', 'Corio', 'Norlane', 'Lara', 'Avalon', 'Little River', 'Anakie'] },
  { key: 'frankston-south',  name: 'Frankston South',  state: 'VIC', type: 'metro',    parentCity: 'Melbourne', subs: ['Frankston', 'Langwarrin South', 'Baxter', 'Somerville', 'Tyabb', 'Pearcedale', 'Tooradin', 'Cranbourne'] },
  { key: 'oakleigh',         name: 'Oakleigh',         state: 'VIC', type: 'metro',    parentCity: 'Melbourne', subs: ['Clayton', 'Huntingdale', 'Springvale', 'Mulgrave', 'Wheelers Hill', 'Notting Hill', 'Clarinda', 'Heatherton'] },
  { key: 'reservoir',        name: 'Reservoir',        state: 'VIC', type: 'metro',    parentCity: 'Melbourne', subs: ['Preston', 'Thornbury', 'Northcote', 'Coburg North', 'Bundoora', 'Heidelberg West', 'Alphington', 'Fairfield'] },
  { key: 'hoppers-crossing', name: 'Hoppers Crossing',  state: 'VIC', type: 'growth',  parentCity: 'Melbourne', subs: ['Werribee', 'Wyndham Vale', 'Tarneit', 'Point Cook', 'Williams Landing', 'Laverton', 'Altona Meadows', 'Little River'] },
  { key: 'cranbourne',       name: 'Cranbourne',       state: 'VIC', type: 'growth',   parentCity: 'Melbourne', subs: ['Clyde', 'Clyde North', 'Botanic Ridge', 'Pearcedale', 'Hampton Park', 'Lynbrook', 'Lyndhurst', 'Narre Warren South'] },
  { key: 'warragul',         name: 'Warragul',         state: 'VIC', type: 'regional', subs: ['Drouin', 'Yarragon', 'Trafalgar', 'Moe', 'Morwell', 'Traralgon', 'Leongatha', 'Korumburra'] },
  { key: 'wangaratta',       name: 'Wangaratta',       state: 'VIC', type: 'regional', subs: ['Oxley', 'Milawa', 'Everton', 'Beechworth', 'Bright', 'Myrtleford', 'Whorouly', 'Tarrawingee'] },
  { key: 'morwell',          name: 'Morwell',          state: 'VIC', type: 'regional', subs: ['Traralgon', 'Moe', 'Churchill', 'Yallourn North', 'Newborough', 'Trafalgar', 'Rawson', 'Erica'] },
  { key: 'horsham',          name: 'Horsham',          state: 'VIC', type: 'regional', subs: ['Natimuk', 'Dimboola', 'Nhill', 'Stawell', 'Ararat', 'Warracknabeal', 'Hopetoun', 'Rainbow'] },
  { key: 'upper-coomera',    name: 'Upper Coomera',    state: 'QLD', type: 'growth',   parentCity: 'Gold Coast', subs: ['Coomera', 'Pimpama', 'Ormeau', 'Jacobs Well', 'Helensvale', 'Oxenford', 'Maudsland', 'Willow Vale'] },
  { key: 'springwood-qld',   name: 'Springwood',       state: 'QLD', type: 'metro',    parentCity: 'Brisbane', subs: ['Daisy Hill', 'Shailer Park', 'Slacks Creek', 'Underwood', 'Rochedale South', 'Cornubia', 'Loganholme', 'Tanah Merah'] },
  { key: 'narangba',         name: 'Narangba',         state: 'QLD', type: 'growth',   parentCity: 'Brisbane', subs: ['Burpengary', 'Morayfield', 'Caboolture', 'North Lakes', 'Kallangur', 'Petrie', 'Strathpine', 'Mango Hill'] },
  { key: 'deception-bay',    name: 'Deception Bay',    state: 'QLD', type: 'metro',    parentCity: 'Brisbane', subs: ['Redcliffe', 'Kippa-Ring', 'Rothwell', 'Clontarf', 'Margate', 'Newport', 'Scarborough', 'Woody Point'] },
  { key: 'sunshine-coast-hinterland', name: 'Sunshine Coast Hinterland', state: 'QLD', type: 'regional', subs: ['Maleny', 'Montville', 'Mapleton', 'Nambour', 'Yandina', 'Eumundi', 'Cooroy', 'Pomona'] },
  { key: 'innisfail',        name: 'Innisfail',        state: 'QLD', type: 'regional', subs: ['Mission Beach', 'Tully', 'Babinda', 'Gordonvale', 'Mareeba', 'Atherton', 'Malanda', 'Ravenshoe'] },
  { key: 'busselton',        name: 'Busselton',        state: 'WA',  type: 'coastal',  subs: ['Dunsborough', 'Quindalup', 'Yallingup', 'Cowaramup', 'Margaret River', 'Vasse', 'Broadwater', 'Abbey'] },
  { key: 'swan',             name: 'Swan',             state: 'WA',  type: 'metro',    parentCity: 'Perth', subs: ['Midvale', 'Guildford', 'Bassendean', 'Bayswater', 'Morley', 'Noranda', 'Beechboro', 'Bennett Springs'] },
  { key: 'stirling',         name: 'Stirling',         state: 'WA',  type: 'metro',    parentCity: 'Perth', subs: ['Scarborough', 'Doubleview', 'Karrinyup', 'Duncraig', 'Innaloo', 'Osborne Park', 'Balga', 'Nollamara'] },
  { key: 'gosnells',         name: 'Gosnells',         state: 'WA',  type: 'metro',    parentCity: 'Perth', subs: ['Maddington', 'Kenwick', 'Thornlie', 'Southern River', 'Canning Vale', 'Langford', 'Huntingdale', 'Martin'] },
  { key: 'mundaring',        name: 'Mundaring',        state: 'WA',  type: 'regional', subs: ['Midland', 'Kalamunda', 'Boya', 'Parkerville', 'Darlington', 'Glen Forrest', 'Chidlow', 'Sawyers Valley'] },
  { key: 'port-pirie',       name: 'Port Pirie',       state: 'SA',  type: 'regional', subs: ['Port Augusta', 'Whyalla', 'Crystal Brook', 'Gladstone', 'Jamestown', 'Peterborough', 'Orroroo', 'Laura'] },
  { key: 'norwood',          name: 'Norwood',          state: 'SA',  type: 'metro',    parentCity: 'Adelaide', subs: ['Kensington', 'Marryatville', 'Rose Park', 'Burnside', 'Magill', 'Erindale', 'Campbelltown SA', 'Newton'] },
  { key: 'unley',            name: 'Unley',            state: 'SA',  type: 'metro',    parentCity: 'Adelaide', subs: ['Parkside', 'Millswood', 'Goodwood', 'Clarence Park', 'Black Forest', 'Malvern', 'Fullarton', 'Hyde Park'] },
  { key: 'marion',           name: 'Marion',           state: 'SA',  type: 'metro',    parentCity: 'Adelaide', subs: ['Sturt', 'Mitchell Park', 'Oaklands Park', 'Park Holme', 'Seacombe Gardens', 'Trott Park', 'Hallett Cove', 'Sheidow Park'] },
  { key: 'west-torrens',     name: 'West Torrens',     state: 'SA',  type: 'metro',    parentCity: 'Adelaide', subs: ['Lockleys', 'Underdale', 'Torrensville', 'Netley', 'Cowandilla', 'Brooklyn Park', 'Richmond SA', 'Mile End'] },
  { key: 'onkaparinga',      name: 'Onkaparinga',      state: 'SA',  type: 'metro',    parentCity: 'Adelaide', subs: ['Noarlunga', 'Christies Beach', 'Morphett Vale', 'Reynella', 'Hackham', 'Woodcroft', 'Seaford', 'Aldinga Beach'] },
  { key: 'sorell',           name: 'Sorell',           state: 'TAS', type: 'regional', subs: ['Midway Point', 'Dodges Ferry', 'Dunalley', 'Forcett', 'Lewisham', 'Penna', 'Taranna', 'Orford'] },
  { key: 'huon-valley',      name: 'Huon Valley',      state: 'TAS', type: 'regional', subs: ['Huonville', 'Geeveston', 'Dover', 'Cygnet', 'Franklin', 'Ranelagh', 'Judbury', 'Southport TAS'] },
  { key: 'central-highlands-tas', name: 'Central Highlands TAS', state: 'TAS', type: 'regional', subs: ['Queenstown', 'Strahan', 'Rosebery', 'Zeehan', 'Tullah', 'Gormanston', 'Queenstown East', 'Linda'] },
  { key: 'tennant-creek',    name: 'Tennant Creek',    state: 'NT',  type: 'regional', subs: ['Elliott', 'Renner Springs', 'Ali Curung', 'Banka Banka', 'Newcastle Waters', 'Dunmarra', 'Daly Waters', 'Mataranka'] },
  { key: 'woden',            name: 'Woden Valley',     state: 'ACT', type: 'metro',    parentCity: 'Canberra', subs: ['Phillip', 'Woden', 'Curtin', 'Garran', 'Hughes', 'Lyons', 'Mawson', 'Torrens'] },
  { key: 'inner-north-canberra', name: 'Inner North Canberra', state: 'ACT', type: 'metro', parentCity: 'Canberra', subs: ['Braddon', 'Turner', 'Dickson', 'Hackett', 'Watson', 'Downer', 'Ainslie', 'Campbell'] },
  { key: 'south-canberra',   name: 'South Canberra',   state: 'ACT', type: 'metro',    parentCity: 'Canberra', subs: ['Kingston', 'Griffith', 'Narrabundah', 'Forrest', 'Red Hill', 'Deakin', 'Yarralumla', 'Barton'] },
  { key: 'molonglo',         name: 'Molonglo Valley',  state: 'ACT', type: 'growth',   parentCity: 'Canberra', subs: ['Wright', 'Coombs', 'Denman Prospect', 'Whitlam', 'Tarrant', 'Coombs', 'Cooleman Ridge', 'Chapman'] },
  { key: 'katherine-region', name: 'Katherine Region', state: 'NT',  type: 'regional', subs: ['Katherine', 'Mataranka', 'Larrimah', 'Daly Waters', 'Timber Creek', 'Kununurra', 'Wyndham', 'Halls Creek'] },
]
